### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by simaguo** [chobits/ngx_http_proxy_connect_module#1]
../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c: In function 'ngx_http_proxy_connect_read_upstream':
../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:585:42: error: variable 'plcf' set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.o] Error 1
make[1]: Leaving directory `/usr/local/src/nginx-1.9.2'
make: *** [build] Error 2

**Comment by chobits** [comment]
hi @simaguo , thanks for report, I have fixed this compilation error in latest master branch. You can check latest master.

(bugfix commit is: https://github.com/chobits/ngx_http_proxy_connect_module/commit/88916d734d02ea10e02698f6d4c278e822f2679b)

**Comment by chobits** [comment]
Consider it resolved. I'm closing this issue.
If you are still seeing this, feel free to reopen it.
