### ISSUE TITLE
client error: curl: (56) Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by yangruizeng** [chobits/ngx_http_proxy_connect_module#100]
我的配置：
```
nginx.conf是默认配置
proxy.conf:
 server {
     listen                         8080;

     # dns resolver used by forward proxying
     resolver                       8.8.8.8;

     # forward proxy for CONNECT request
     proxy_connect;
     proxy_connect_allow            443 563;
     proxy_connect_connect_timeout  110s;
     proxy_connect_read_timeout     110s;
     proxy_connect_send_timeout     110s;

     # forward proxy for non-CONNECT request
     location / {
         proxy_pass http://$host;
         proxy_set_header Host $host;
     }
}
```

```curl 'https://github.com' -x "myip:8080"   ```  # 请求github是正常的，在google浏览器配置代理也是可以正常访问的
但是请求google或者其他一些地址就有问题，比如：
```
curl "https://scontent-hkg3-2.cdninstagram.com/vp/e89bede1844ec5c2c7b52a8fd7ec7ac5/5D728D1E/t51.2885-15/sh0.08/e35/s640x640/56297028_451858225637225_6484710113882897545_n.jpg?_nc_ht=scontent-hkg3-2.cdninstagram.com" -x "myip:8080" 
  返回：curl: (56) Recv failure: Connection reset by peer
```

日志中报错信息：
```
==> ../../logs/error.log <==
2019/04/21 02:18:56 [info] 1167#0: *2650 client prematurely closed connection (104: Connection reset by peer), client: 106.117.68.9, server: , request: "CONNECT scontent-hkg3-2.cdninstagram.com:443 HTTP/1.1", host: "scontent-hkg3-2.cdninstagram.com:443"

==> ../../logs/access.log <==
106.117.68.9 - - [21/Apr/2019:02:18:56 +0800] "CONNECT scontent-hkg3-2.cdninstagram.com:443 HTTP/1.1" 499 0 "-" "curl/7.54.0" "-"

```
排查了很长时间都没有解决，求帮助

**Comment by chobits** [comment]
这样看来是你浏览器的连接行为被中间设备做双向断链了。因为某些特殊原因。

**Comment by chobits** [comment]
may be resolved, feel free to reopen if you still have any problem

**Comment by aa3222119** [comment]
差不多一样的问题，baidu，github成功，youtube和google 499 ，请问目前有什么好的解决办法了嘛？
`* Recv failure: Connection reset by peer
* Received HTTP code 0 from proxy after CONNECT
* Connection #0 to host 43.128.68.117 left intact`

**Comment by aa3222119** [comment]
same issue ，it works on github，but 499 when i curl youtube.com and google.com，does it has nice solution now?
` 
* Establish HTTP proxy tunnel to google.com:443
> CONNECT google.com:443 HTTP/1.1
> Host: google.com:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
> 
* Recv failure: Connection reset by peer
* Received HTTP code 0 from proxy after CONNECT
* Connection #0 to host x.x left intact`

**Comment by JokerSora** [comment]
- - [19/Apr/2023:22:10:46 +0800] "CONNECT www.google.com:443 HTTP/1.1" 499 0 "-" "curl/7.83.1"
- - [19/Apr/2023:22:25:47 +0800] "CONNECT www.github.com:443 HTTP/1.1" 200 2896 "-" "curl/7.83.1"
anyone could tell me why?

**Comment by chobits** [comment]
> * * [19/Apr/2023:22:10:46 +0800] "CONNECT [www.google.com:443](http://www.google.com:443) HTTP/1.1" 499 0 "-" "curl/7.83.1"
> * * [19/Apr/2023:22:25:47 +0800] "CONNECT [www.github.com:443](http://www.github.com:443) HTTP/1.1" 200 2896 "-" "curl/7.83.1"
>     anyone could tell me why?

Proxy module attempted to connect to the backend server 'google.com' on your access log, but it took an excessively long time to establish the connection.  As as result, the client terminated the connection and nginx recorded it as a status code of 499.

You can ask your network service provider why some websites may be accessible while others are not, such as [google.com](http://google.com).

**Comment by fkeaai** [comment]
same issue here ,no for google and youtube

**Comment by lloydzhou** [comment]
i see this [comment](https://github.com/chobits/ngx_http_proxy_connect_module/issues/281#issuecomment-2003135042)
then using ssl to solve same issue.
