### ISSUE TITLE
Only garbage was found in the patch input

### ISSUE THREAD

**Issue by jsEveryDay** [chobits/ngx_http_proxy_connect_module#105]
Sorry for opening a new issue. Could you please advise? I keep getting the same compilation error due to the unsuccessful patch. Running Centos7 GNU patch 2.7.1

yum install pcre-devel zlib-devel openssl-devel patch -y
wget http://nginx.org/download/nginx-1.15.12.tar.gz
tar -zxvf *.tar.gz
wget https://github.com/chobits/ngx_http_proxy_connect_module/blob/master/patch/proxy_connect_rewrite_101504.patch
cd nginx-1.15.12

patch -p1 < /root/nginx/proxy_connect_rewrite_101504.patch
### **patch: **** Only garbage was found in the patch input.** --This is literally the message I am getting.

cd ../
git clone https://github.com/chobits/ngx_http_proxy_connect_module.git
cd nginx-1.15.12
./configure --add-module=/root/nginx/ngx_http_proxy_connect_module
make

Errors..

I'd really appreciate it, I really want this to work. Will respond promptly this time.

**Comment by jsEveryDay** [comment]
So silly. Was getting the non raw git URL.

https://raw.githubusercontent.com/chobits/ngx_http_proxy_connect_module/master/patch/proxy_connect_rewrite_101504.patch

**Comment by chobits** [comment]
Yes, should use raw git URL:)
