### ISSUE TITLE
Whether keepalive are supported ?

### ISSUE THREAD

**Issue by xxm404** [chobits/ngx_http_proxy_connect_module#107]
Forward request can support keepalive ?

**Comment by chobits** [comment]
proxy_connect module always makes connection keepalive within timeout set by `proxy_connect_read_timeout` and `proxy_connect_send_timeout `.

However, note that proxy_connect module only keep TCP connection alive. Whether tcp connection is keepalived by remote server depends on remote server and data protocol of tcp stream, which is not controlled by this module.

**Comment by chobits** [comment]
think it resolved? hi , I am closing issue.

Feel free to reopen if you still have any problem:)
