### ISSUE TITLE
how to specify next-hop ip address of proxied squid server?

### ISSUE THREAD

**Issue by berny9015** [chobits/ngx_http_proxy_connect_module#118]

**Comment by berny9015** [comment]
$connect_host
host name from CONNECT request line.

$connect_port
port from CONNECT request line.

$connect_addr
IP address and port of the remote host, e.g. "192.168.1.5:12345". IP address is resolved from host name of CONNECT request line.
是使用以上的变量么，我试了一下，都报错 nginx: [emerg] unknown directive "connect_addr，请问具体如何使用，多谢？

**Comment by chobits** [comment]
You can use [proxy_connect_address](https://github.com/chobits/ngx_http_proxy_connect_module#proxy_connect_address) directive to specify IP address of the squid.

**Comment by chobits** [comment]
Example of proxy_connect_address:

```
        proxy_connect;
        proxy_connect_allow all;
        proxy_connect_address 127.0.0.1:8082;
```

**Comment by berny9015** [comment]
I have tested it, but it still shows the IP of the server. Here is my configuration：

       # forward proxy for CONNECT request
        proxy_connect;
        proxy_connect_allow            all;
        proxy_connect_connect_timeout  10s;
        proxy_connect_read_timeout     10s;
        proxy_connect_send_timeout     10s;
        proxy_connect_address 114.233.49.243:23333;

        location / {
          proxy_pass http://$host;
          proxy_set_header Host $host;
        }

Check at httpbin.org:
{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Host": "httpbin.org", 
    "User-Agent": "python-requests/2.22.0"
  }, 
  "origin": "120.27.60.201, 120.27.60.201", 
  "url": "https://httpbin.org/get"
}

**Comment by chobits** [comment]
>  but it still shows the IP of the server

I dont know what your problem is.

> Check at httpbin.org:

What is your network model? 

And please describe what you expected to happen.


> proxy_connect_address 114.233.49.243:23333;

This directive means it will proxy CONNECT-tunnel traffic to endpoint 114.233.49.243:23333.
Note that your client should send CONNECT request first then send raw stream from the connection.

**Comment by liuchenx** [comment]
@berny9015 解决了这个问题吗 
` 
server {
       resolver 8.8.8.8;
       listen                         8355;
       proxy_connect;
       proxy_connect_allow            all;
       proxy_connect_connect_timeout  10s;
       proxy_connect_read_timeout     10s;
       proxy_connect_send_timeout     10s;
       proxy_connect_address 127.0.0.1:3128;
       location / {
           proxy_pass http://$host;
           proxy_set_header Host $host;
       }
    }
`
这是我的配置127.0.0.1:3128是下一跳squid的地址输入命令
`
curl -k https://github.com/ -v -x 127.0.0.1:8355
`
显示错误：
`
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8355 (#0)
* Establish HTTP proxy tunnel to github.com:443
> CONNECT github.com:443 HTTP/1.1
> Host: github.com:443
> User-Agent: curl/7.47.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection Established
< Proxy-agent: nginx
< 
* Proxy replied OK to CONNECT request
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: An unexpected TLS packet was received.
* Closing connection 0
curl: (35) gnutls_handshake() failed: An unexpected TLS packet was received.
`

**Comment by chobits** [comment]
hi @liuchenx 


> gnutls_handshake() failed: An unexpected TLS packet was received.
> Closing connection 0
> curl: (35) gnutls_handshake() failed: An unexpected TLS packet was received.

The connect-tunnel worked well for your case, in which case the connect tunnel has been established and raw stream( https request for github.com) has been proxied to backend server (squid).

But the squid server failed to do SSL handshake, may your squid server is not configured to server SSL request.

**Comment by chobits** [comment]
@berny9015 ping? 

Has it been solved?

**Comment by chobits** [comment]
think it resolved. Feel free to comment if you still have this problem.

**Comment by elmemis** [comment]
I have the same problem.

I need add "Certificate Authentication" to SQUID and I have chosen to put an nginx in front of the squid. My SQUID have SSL Bump configured.

My NGINX conf:
`
    upstream _squid {
        server 192.168.1.10:31288;
    }
    server {
        listen 33334;
        error_log  /var/log/nginx/error.33334.log debug;
        access_log  /var/log/nginx/host.33334.log  main;
        proxy_set_header Host            $host;
        proxy_set_header X-Real-IP       $proxy_protocol_addr;
        proxy_set_header X-Forwarded-For $proxy_protocol_addr;

        proxy_connect;
        proxy_connect_address   192.168.1.10:31288;
        proxy_connect_allow            all;
        proxy_connect_connect_timeout  10s;
        proxy_connect_read_timeout     10s;
        proxy_connect_send_timeout     10s;
        location / {
                proxy_pass       http://_squid;
                proxy_set_header Host            $host;
                proxy_set_header X-Real-IP       $proxy_protocol_addr;
                proxy_set_header X-Forwarded-For $proxy_protocol_addr;
                #proxy_pass http://_squid;
                #proxy_set_header Host $host;
        }
}
`

My SQUID config:
`
http_port 31288 ssl-bump cert=/etc/squid/ssl_cert/AbitabCA.pem key=/etc/squid/ssl_cert/Abitab.pem generate-host-certificates=on dynamic_cert_mem_cache_size=4MB
sslcrtd_program /usr/lib64/squid/ssl_crtd -s /var/lib/squid/ssl_db -M 4MB
sslcrtd_children 8 startup=1 idle=1

always_direct allow all
ssl_bump server-first all
ssl_bump bump all
sslproxy_cert_error allow all
sslproxy_flags DONT_VERIFY_PEER
`

Curl output:
`
curl -x 192.168.1.9:33334 https://vermiip.es -v -k
* Rebuilt URL to: https://vermiip.es/
*   Trying 192.168.1.9...
* TCP_NODELAY set
* Connected to 192.168.1.9 (192.168.1.9) port 33334 (#0)
* Establish HTTP proxy tunnel to vermiip.es:443
> CONNECT vermiip.es:443 HTTP/1.1
> Host: vermiip.es:443
> User-Agent: curl/7.54.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection Established
< Proxy-agent: nginx
<
* Proxy replied OK to CONNECT request
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
* stopped the pause stream!
* Closing connection 0
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
`
