### ISSUE TITLE
How to log upstream_response_time?

### ISSUE THREAD

**Issue by sunfuze** [chobits/ngx_http_proxy_connect_module#120]
Now the access_log just log request_time.
Are there any ways to know backend `server -> nginx` response time?

**Comment by sunfuze** [comment]
> Now the access_log just log request_time.
> Are there any ways to know backend `server -> nginx` response time?

this is my log_format

```
 log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                   '$status $body_bytes_sent "$http_referer" '
                   '"$http_user_agent" "$http_x_forwarded_for" '
                   'rt=$request_time uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';
```
this is output:

```

18.162.91.224 - - [26/Jul/2019:09:37:27 +0000] "CONNECT example.com:443 HTTP/1.1" 200 5447 "-" "Go-http-client/1.1" "-" rt=0.178 uct="-" uht="-" urt="-"
```

**Comment by chobits** [comment]
Hi @sunfuze 

Your problem could be hard to resolve. Let me explain

After creating connect-tunnel with backend server,  the nginx(proxy_connect) module only transfers raw stream to backend, it does not parse the stream or requests in the stream. So it cannot log the upstream time of requests in the proxied raw stream.

All statiscs that could be logged has been showed in the [doc/variables](https://github.com/chobits/ngx_http_proxy_connect_module#variables).

**Comment by sunfuze** [comment]
Thx for you explaining. I have one more question about connection keep alive timeout. A client have 300s keepalive timeout and a proxied server have 60s keepalive timeout, the real keepalive timeout is 300s or 60s?

**Comment by chobits** [comment]
> Thx for you explaining. I have one more question about connection keep alive timeout. A client have 300s keepalive timeout and a proxied server have 60s keepalive timeout, the real keepalive timeout is 300s or 60s?

The minumum value will work, so it is 60s.

Also note that the keepalive timeout works on request, but proxy_connect(ngx) module only works on the level of connection session with backend server. In such case, [proxy_connect_read_timeout](https://github.com/chobits/ngx_http_proxy_connect_module#proxy_connect_read_timeout) works instead of upstream keepalive timeout.

**Comment by sunfuze** [comment]
> > Thx for you explaining. I have one more question about connection keep alive timeout. A client have 300s keepalive timeout and a proxied server have 60s keepalive timeout, the real keepalive timeout is 300s or 60s?
> 
> The minumum value will work, so it is 60s.
> 
> Also note that the keepalive timeout works on request, but proxy_connect(ngx) module only works on the level of connection session with backend server, it is L4 tcp proxy server, not L7 request proxy server. In such case,
> 
> * [proxy_connect_read_timeout](https://github.com/chobits/ngx_http_proxy_connect_module#proxy_connect_read_timeout) works instead of upstream keepalive timeout.
> * `client_body_timeout` works instead of client keepalive timeout for two successive read operations, not for the transmission of the whole http response.

Thx, Really helpful for me.
