### ISSUE TITLE
Raspberry Pi 3B Buster Compile Problem

### ISSUE THREAD

**Issue by onurzaim** [chobits/ngx_http_proxy_connect_module#131]
### 0. Before Your ASK

1. Try to find an answer by reading a [FAQ](https://github.com/chobits/ngx_http_proxy_connect_module/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aquestion).

### Ⅰ. Issue Description
 Does not compile with raspberry pi Debian Buster

### Ⅱ. Describe what happened

In file included from src/http/ngx_http_core_module.c:9:
src/http/ngx_http_core_module.c: In function ‘ngx_http_update_location_config’:
src/core/ngx_core.h:37:25: error: ‘return’ with a value, in function returning void [-Werror]
 #define  NGX_AGAIN      -2
                         ^
src/http/ngx_http_core_module.c:1228:16: note: in expansion of macro ‘NGX_AGAIN’
         return NGX_AGAIN;
                ^~~~~~~~~
src/http/ngx_http_core_module.c:1221:1: note: declared here
 ngx_http_update_location_config(ngx_http_request_t *r)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:840: objs/src/http/ngx_http_core_module.o] Error 1
make[1]: Leaving directory '/root/nginx-1.14.2'
make: *** [Makefile:8: build] Error 2

### Ⅲ. Describe what you expected to happen

It should have compiled without error

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

wget http://nginx.org/download/nginx-1.14.2.tar.gz
tar -xvzf nginx-1.14.2.tar.gz
cd nginx-1.14.2
patch -p1 < /root/ngx_http_proxy_connect_module/patch/proxy_connect_rewrite.patch
./configure --add-dynamic-module=/root/ngx_http_proxy_connect_module/
make

1.
2.
3.

### Ⅴ. Anything else we need to know?

1. If applicable, add nginx  [debug log](http://nginx.org/en/docs/debugging_log.html).
2.
3.

### Ⅵ. Environment:

1. Tengine/Nginx/OpenResty version (use `sbin/nginx -v`):

nginx 1.14.2
2. Which [patch](https://github.com/chobits/ngx_http_proxy_connect_module#select-patch) do you use?
proxy_connect_rewrite.patch

**Comment by chobits** [comment]
Let me check.

**Comment by chobits** [comment]
Hi, @onurzaim 

> 2. Which patch do you use?
> proxy_connect_rewrite.patch

 proxy_connect_rewrite.patch is used by nginx 1.`4`.x, not 1.`14`.x

Try this patch: [proxy_connect_rewrite_1014.patch](https://github.com/chobits/ngx_http_proxy_connect_module/blob/master/patch/proxy_connect_rewrite_1014.patch), it will work well.

**Comment by chobits** [comment]
hi @onurzaim 

Have you resolved this issue?

**Comment by chobits** [comment]
Think it resolved, incorrect patch used.
