### ISSUE TITLE
nginx 1.14 and above compile error

### ISSUE THREAD

**Issue by jeremy168** [chobits/ngx_http_proxy_connect_module#135]
Do you know if there is any maintenance for this module?

I currently encounter a problem, that is, I am compiling nginx version 1.14 and above
http_core module compilation, I later used nginx 1.9.2 version without this one
Problems occur, such as if the author of the proxy_connect module can improve it, or is there something missing?Something is missing, thank you, provide 1.17 and 1.15 error messages

The current system is centos 7.7

請問不知道這一個模組還有再維護嗎?

我目前遇到一個問題,就是我在編譯nginx 版本1.14以上版本都發生在
http_core 模組編譯情況,我後來使用 nginx 1.9.2版本就沒有這一個
問題發生囉,如撰寫proxy_connect 模組作者是否可改善一下,還是有缺
少什麼物件產生的,謝謝你,提供1.17和1.15版本錯誤訊息

![nginx1159](https://user-images.githubusercontent.com/58226202/71469105-1d4fbf80-2803-11ea-9a8e-d92f4804e884.JPG)
![nginx1177](https://user-images.githubusercontent.com/58226202/71469106-1d4fbf80-2803-11ea-8b99-86c7417024f1.JPG)

**Comment by chobits** [comment]
From ur compilation error, it may be wrong patch used. Which path do u use for your nginx-1.14+?

For details of which patch should be used for each version of nginx, see [this link](https://github.com/chobits/ngx_http_proxy_connect_module#select-patch).

**Comment by chobits** [comment]
ping? Think it resolved, if u still has this problem, please reopen!
