### ISSUE TITLE
[Feature request] whitelist hostnames

### ISSUE THREAD

**Issue by DanPM** [chobits/ngx_http_proxy_connect_module#140]
Thank you for module.
Is there any way to whitelist only particular domains to allow proxy forwarding?
Any ideas on workarounds? Unfortunately I can't do this in Firewall (political reasons).

**Comment by jhecking** [comment]
I need this feature as well. One possible solution I found is to use an `if` statement like this to check the host in the CONNECT request:

```
    if ($connect_host !~ ^www.google.com$) {
      return 403;
    }
```

This has to be placed _outside_ the `location /` context.

When you try to connect to a host other than `www.google.com` the request is rejected:

```
> curl -sS -x localhost https://www.yahoo.com > /dev/null
curl: (56) Received HTTP code 403 from proxy after CONNECT
> curl -sS -x localhost https://www.google.com > /dev/null
```

**Comment by check4game** [comment]
map $connect_host $is_host_deny{
default 1;
"host1.com" 0;
"host1.com" 0;
"host1.com" 0;
}

if ($is_host_deny) {
      return 403;
}

**Comment by DanPM** [comment]
Thank you for your comments and solution. This solves my issue.

**Comment by grayguest** [comment]
> map $connect_host $is_host_deny{ default 1; "host1.com" 0; "host1.com" 0; "host1.com" 0; }
> 
> if ($is_host_deny) { return 403; }

Pay attention, It also restrict visit http:// website
