### ISSUE TITLE
Proxy to another HTTP proxy

### ISSUE THREAD

**Issue by huangsuoyuan** [chobits/ngx_http_proxy_connect_module#142]
Can I use this module to proxy this request to one or more HTTP proxy servers. 

The process would be like

Client ---> Nginx(with proxy connect module) ---> real HTTP proxy server ---> target website

The background for this question is:
We bought real HTTP proxy servers from external provider.
We want to add access control through Nginx

**Comment by chobits** [comment]
> --> real HTTP proxy server ---> target website

For this proxying phase, if the `target website` works under SSL protocol, it cannot work. Your `real HTTP proxy server` cannot get the real SSL certificate, and the browser will refuse to work.
