### ISSUE TITLE
Metrics to track dns resolution/connection timings

### ISSUE THREAD

**Issue by jrgp** [chobits/ngx_http_proxy_connect_module#144]
## Why you need it?

Being  able to track how long dns resolution as well as connection establishment takes  would  help debug issues where we're unsure why  a  request took so long.

All we currently have is `$request_time` which is good for determining how long the entire request took, but it is not granular enough for debugging purposes.

## How it could be?

Create metrics (variables) equivalent to $upstream_connect_time and one for dns resolution, which could then be used within log_format

**Comment by chobits** [comment]
Thanks for reporting, its useful to debu.  I'll try to resolve it after updating this module for latest nginx release.

**Comment by chobits** [comment]
hi @jrgp 

I have added new feature to resolve this issue, see my new pr:https://github.com/chobits/ngx_http_proxy_connect_module/pull/154.

Two new variables [$proxy_connect_resolve_time](https://github.com/chobits/ngx_http_proxy_connect_module#proxy_connect_resolve_time) and [$proxy_connect_connect_time](https://github.com/chobits/ngx_http_proxy_connect_module#proxy_connect_connect_time)

**Comment by chobits** [comment]
Think it resolved, I'm closing this issue, thanks for reporting!
