### ISSUE TITLE
无法代理代理证书接口

### ISSUE THREAD

**Issue by lingo169** [chobits/ngx_http_proxy_connect_module#149]
我想代理https://api.mch.weixin.qq.com/secapi/mkt/addrecommendconf这个接口，
该接口是需要证书才能访问的，目前我直接访问接口是可以的，但是通过connect_module进行代理，则无法访问，配置如下：
`server {

      listen      82;
      # dns resolver used by forward proxying
      resolver                       8.8.8.8;

      # forward proxy for CONNECT request
      proxy_connect;
      proxy_connect_allow            443 563;
      proxy_connect_connect_timeout  10s;
      proxy_connect_read_timeout     10s;
      proxy_connect_send_timeout     10s;

      # forward proxy for non-CONNECT request
      location / {
          proxy_pass https://api.mch.weixin.qq.com;
          proxy_set_header Host $host;
      }
    }`

请问需要怎么配置呢？

**Comment by chobits** [comment]
你访问的时候你的客户端不能用正常的https访问方式，需要开启正向代理才可以。

如果是curl的话，则

```
curl https://api.mch.weixin.qq.com/secapi/mkt/addrecommendconf  -v -x <你的服务器 ip>:<你的服务器 port>
```

如果是浏览器的话，则参考https://github.com/chobits/ngx_http_proxy_connect_module/issues/22#issuecomment-346941271

如果是自制客户端，需要编程支持正向代理

**Comment by chobits** [comment]
Hi

 Still there? I am closing this issue, if you still have this issue, please reopen  it!
