### ISSUE TITLE
Question about TLS Certificate

### ISSUE THREAD

**Issue by jozhuzhu** [chobits/ngx_http_proxy_connect_module#151]
After reading README.md, I found it is tested by 
```
curl https://www.baidu.com -v -x ee.eee.eee.ee
```
If I build a https server by myself, how should i do to assign specific certificate in curl to simulate a https request using proxy ?

**Comment by chobits** [comment]
Hi

 Still there? I am closing this issue, if you still have this issue, please reopen  it!
