### ISSUE TITLE
error when i try to install on ubuntu 16 64 bits

### ISSUE THREAD

**Issue by ingnelson** [chobits/ngx_http_proxy_connect_module#156]
hello.

when i try to install nginx using this command :

patch -p1 < /path/to/ngx_http_proxy_connect_module/patch/proxy_connect.patch

show the next error : 
/path/to/ngx_http_proxy_connect_module/patch/proxy_connect.patch: No such file or directory

help please.

**Comment by chobits** [comment]
hi,

`/path/to/ngx_http_proxy_connect_module/patch/proxy_connect.patch` is only an example, not right patch path. Please find the right file path in your computer.

**Comment by chobits** [comment]
Also note that `proxy_connect.patch` is used for old nginx version, see [this page](https://github.com/chobits/ngx_http_proxy_connect_module#select-patch) for how to select patch.
