### ISSUE TITLE
[Docker, nginx 1.18] .so file not produced by the build

### ISSUE THREAD

**Issue by DawidJanczak** [chobits/ngx_http_proxy_connect_module#158]
Hello!

I'm trying to build this module inside docker and there are no errors during the build, but the .so file is not produced and enabling `proxy_connect` in the config fails. Here are the links to the Dockerfile used to build the image: https://gist.github.com/DawidJanczak/2f7201ea427d2edbc1fa3349b7f70f1c and the build output https://gist.github.com/DawidJanczak/01457468e84cc2d0c1bc2b388f852e21, I listed the modules at the end of the build and I don't see the relevant .so for proxy connect there. I'd appreciate some help :)

**Comment by rbakhtaraev** [comment]
Hi!

I am also trying to build this module as dynamic and found your issue. Your mistake is that you use --add-module instead of --add-dynamic-module.

After replacing the command with the correct one, you can find the module in the directory /usr/local/nginx/modules/

**Comment by DawidJanczak** [comment]
Ah perfect, thank you so much for this @rbakhtaraev!

**Comment by chobits** [comment]
Thanks for @rbakhtaraev , your answer is useful!
