### ISSUE TITLE
OpenResty 1.17.8.1 is out

### ISSUE THREAD

**Issue by kirooshu** [chobits/ngx_http_proxy_connect_module#159]
## Why you need it?

Updating the docs to make sure people are aware that it is supported in this module.

Thanks!

**Comment by chobits** [comment]
Thanks for reporting, I'll test it and update the README!

**Comment by chobits** [comment]
I have tested openresty 1.17.8.2, see [this report](https://github.com/chobits/ngx_http_proxy_connect_module/pull/161#issuecomment-663391244).
