### ISSUE TITLE
gitlab 代理有问题

### ISSUE THREAD

**Issue by spacexnasa** [chobits/ngx_http_proxy_connect_module#160]
配置正常，curl 可以正常使用，但是  

1

git config --global http.proxy http://127.0.0.1:3128
git config --global https.proxy https://127.0.0.1:3128

然后  git clone http://xxxx@gitlab.xxxx.com/xxx/xxx.git 时，报错
The requested URL returned error: 400

错误如下

client sent invalid request while reading client request line, client: 127.0.0.1, server

2
然后新版的 1.19.1 （可能不在兼容列表之类），在配置文件中
 listen  127.0.0.1:3128 或者 
listen 0.0.0.0:3128; 
在使用 nginx -s  relaod 不生效
必须 nginx -s stop && sleep 1 && nginx
才能生效

错误日志如下

2020/07/09 11:23:07 [notice] 23415#23415: reconfiguring
2020/07/09 11:23:07 [emerg] 23415#23415: bind() to 0.0.0.0:3128 failed (98: Address already in use)
2020/07/09 11:23:07 [notice] 23415#23415: try again to bind() after 500ms
2020/07/09 11:23:07 [emerg] 23415#23415: bind() to 0.0.0.0:3128 failed (98: Address already in use)
2020/07/09 11:23:07 [notice] 23415#23415: try again to bind() after 500ms
2020/07/09 11:23:07 [emerg] 23415#23415: bind() to 0.0.0.0:3128 failed (98: Address already in use)
2020/07/09 11:23:07 [notice] 23415#23415: try again to bind() after 500ms
2020/07/09 11:23:07 [emerg] 23415#23415: bind() to 0.0.0.0:3128 failed (98: Address already in use)
2020/07/09 11:23:07 [notice] 23415#23415: try again to bind() after 500ms
2020/07/09 11:23:07 [emerg] 23415#23415: bind() to 0.0.0.0:3128 failed (98: Address already in use)

**Comment by chobits** [comment]
这个应该和这个模块没啥关系。因为我好长时间不做nginx开发了，虽然之前也有遇到过类似问题，但是已经记不清楚具体细节了。

这个就是单纯系统对bind处理的问题。你可以在网上在搜搜，listen本身是有一些隐蔽的坑

**Comment by chobits** [comment]
I tested in my MacOS, cant reproduce also.

```
$ cat nginx.conf
...
    server {
        listen 127.0.0.1:3128;
        listen 0.0.0.0:3128;

        resolver 114.114.114.114 8.8.8.8;

        proxy_connect ;

        # forward proxy for CONNECT method
        proxy_connect;
        proxy_connect_allow all;
        proxy_connect_connect_timeout 10s;
        proxy_connect_read_timeout 10s;
        proxy_connect_send_timeout 10s;
        proxy_connect_send_lowat 0;

    }
}
...

$ $ sbin/nginx -s reload
$ echo $?
0

$ curl https://github.com -x localhost:3128 -I
HTTP/1.1 200 Connection Established
Proxy-agent: nginx

HTTP/1.1 200 OK
date: Fri, 24 Jul 2020 07:11:12 GMT
content-type: text/html; charset=utf-8
server: GitHub.com
status: 200 OK
....
...
```
