### ISSUE TITLE
Ability to add custom CONNECT response headers

### ISSUE THREAD

**Issue by jrgp** [chobits/ngx_http_proxy_connect_module#163]
## Why you need it?

My use case/feature request is determining the connected IP address, by way of an additional special header sent in the initial response to the CONNECT verb.

This would make debugging and introspection of outbound requests easier, as currently it is only possible to determine the connected IP addresses via logs or tcpdump/etc

## How it could be?

Currently, the initial response to the CONNECT header is this hard coded string: https://github.com/chobits/ngx_http_proxy_connect_module/blob/master/ngx_http_proxy_connect_module.c#L12

It would be great if that could optionally be extended, maybe using openresty, to support adding arbitrary headers there including one for the connected IP address

**Comment by chobits** [comment]
We should add new directive, for example:

```
proxy_connect_initial_response "HTTP/1.1 200 Connection Established\r\n\r\n";
``` 

or some writable variable for example

```
rewrite_by_lua {
   ngx.var.proxy_connect_response = "HTTP/1.1 200 Connection Established\r\n\r\n"
};

```

**Comment by jrgp** [comment]
Both of those sounds pretty good to me, especially if they can be set arbitrarily with each request.

**Comment by chobits** [comment]
Hi @jrpg

I have complete this featue in https://github.com/chobits/ngx_http_proxy_connect_module/pull/172.
Added a new variable to custom CONNECT response: `$proxy_connect_response`.

For more details, see doc https://github.com/chobits/ngx_http_proxy_connect_module/tree/for_pull_request#proxy_connect_response.

---


$proxy_connect_response
---------------------------

Get or set the response of CONNECT request.
The default response of CONNECT request is "HTTP/1.1 200 Connection Established\r\nProxy-agent: nginx\r\n\r\n".

Note that it is only used for CONNECT request, it cannot modify the data flow over CONNECT tunnel.

For example:

```nginx

# modify default Proxy-agent header
set $proxy_connect_response "HTTP/1.1 200\r\nProxy-agent: nginx/1.19\r\n\r\n";
```

The variable value does not support nginx variables. You can use lua-nginx-module to construct string that contains nginx variable. For example:

```nginx

# The CONNECT response may be "HTTP/1.1 200\r\nProxy-agent: nginx/1.19.6\r\n\r\n"

rewrite_by_lua '
    ngx.var.proxy_connect_response =
      string.format("HTTP/1.1 200\\r\\nProxy-agent: nginx/%s\\r\\n\\r\\n", ngx.var.nginx_version)
';
```

**Comment by jrgp** [comment]
Hey @chobits thanks for implementing this 👍

One question: when I use the following block, the returned header value is `nil` as opposed to the address:port I'd expect.

```
    rewrite_by_lua_block {
       ngx.var.proxy_connect_response = string.format(
          "HTTP/1.1 200 Connection Established\r\nProxy-agent: nginx\r\nx-proxy-external-ip: %s\r\n\r\n", ngx.var.connect_addr)
    }
```

```
curl -x localhost:$port https://www.google.com -v  2>&1|grep external-ip
< x-proxy-external-ip: nil
```

Is this expected?

**Comment by chobits** [comment]
hi @jrgp 

> Is this expected?

Yes. Because `rewrite_by_lua` or `set` directive is run during REWRITE phase, which is ahead of dns resolving phase. The $connect_addr is caculated after dns resolving phase.

I will give another solution to fix nil variable: added new directive `proxy_connect_response`, which can be run after dns resolving phase.

**Comment by chobits** [comment]
Try new directive [`proxy_connect_response`](https://github.com/chobits/ngx_http_proxy_connect_module#proxy_connect_response) with latest master branch.

---
proxy_connect_response
----------------------

Syntax: **proxy_connect_response `CONNECT response`**
Default: `HTTP/1.1 200 Connection Established\r\nProxy-agent: nginx\r\n\r\n`
Context: `server`

Set the response of CONNECT request.

Note that it is only used for CONNECT request, it cannot modify the data flow over CONNECT tunnel.

For example:

```
proxy_connect_response "HTTP/1.1 200 Connection Established\r\nProxy-agent: nginx\r\nX-Proxy-Connected-Addr: $connect_addr\r\n\r\n";

```

The `curl` command test case with above config is as following:

```
$ curl https://github.com -sv -x localhost:3128
* Connected to localhost (127.0.0.1) port 3128 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to github.com:443
> CONNECT github.com:443 HTTP/1.1
> Host: github.com:443
> User-Agent: curl/7.64.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection Established            --.
< Proxy-agent: nginx                               | custom CONNECT response
< X-Proxy-Connected-Addr: 13.229.188.59:443      --'
...

```

**Comment by jrgp** [comment]
Perfect, that works:

```
$ curl -s -v -x localhost:5901 https://www.google.com 2>&1 | head -n20
* About to connect() to proxy localhost port 5901 (#0)
*   Trying ::1...
* Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5901 (#0)
* Establish HTTP proxy tunnel to www.google.com:443
> CONNECT www.google.com:443 HTTP/1.1
> Host: www.google.com:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection Established
< Proxy-agent: nginx
< X-External-Address: [2607:f8b0:4005:804::2004]:443
```

Thanks a ton. This issue can likely be closed out.
