### ISSUE TITLE
Regarding the Layer7 and Layer4 support for ngx_http_proxy_connect_module, for non -DNS resolvable URIs

### ISSUE THREAD

**Issue by naveen27232** [chobits/ngx_http_proxy_connect_module#164]
Hi 

I have a question -
Referring to https://www.alibabacloud.com/blog/how-to-use-nginx-as-an-https-forward-proxy-server_595799
I have the ngx_http_proxy_connect_module.so loaded dynamically in nginx 1.18.0
and would like to know-

For layer7 solution-
I would like the connection on port 443 with SSL , and certs configured .(Trust established between browser and nginx forward proxy here) 
Then i want to know is it possible to have 
proxy_connect_allow            443
and also trap this CONNECT request , interpret it by seeing the host matching with like 1234-1.2.3.4 (a kind of custom URI) 
and connecting it to a fixed IP 1.2.3.4
similarly if i get a CONNECT request with like  host matching with like 4567-4.5.6.7 (a kind of custom URI) 
and connecting it to a fixed IP 4.5.6.7.
So that the same CONNECT req is forwarded to some IPs by seeing the headers..
How can i do that...any suggestion with the nginx -default.conf

Question for layer 4 solution
proxy_pass $ssl_preread_server_name:$server_port;
Instead of above if i want to do any smartness with checking $ssl_preread_server_name - matching with like custom URI 
4567-4.5.6.7 (a kind of custom URI) 
and connecting it to a fixed IP 4.5.6.7.
So that the same CONNECT req is forwarded to some IPs by seeing the headers..

I tried both things with SSL on 443 and using the same with browsers requests like https://4567-4.5.6.7:443

Request comes to the proxy and does not proxy pass through...
Any suggestions how to have that working...
Note here that - 4567-4.5.6.7 is not a DNS resolvable value , but we would like to route it to an IP as illustrated above..

**Comment by chobits** [comment]
For your `a kind of custom URI`:

Before CONNECT tunnel is established, the CONNECT request has no URI, there is only backend IP/HOST/PORT information.

```
CONNECT example.host.com:22 HTTP/1.1
                   ^-------- No URI information
```

After CONNECT tunnel is established, this module does not parse or operate the data flow over tunnel, it only proxy the raw data.

**Comment by chobits** [comment]
For your 
> So that the same CONNECT req is forwarded to some IPs by seeing the headers.

The requests (raw data flow) over same CONNECT tunnel can only be forwarded to one IP:PORT, which can be chosen by DNS resolver  or customed by yourself via proxy_connect_address directive.

And requests over CONNECT tunnel will not be handled by `proxy_pass` directive(proxy_pass module), they are proxied by proxy_connect module. And proxy_connect module does not know whether they are requests or other protocol, it only proxies *RAW data flow*.
