### ISSUE TITLE
Does this module support usecase where upstream are behind proxy.

### ISSUE THREAD

**Issue by sharma-abhishek** [chobits/ngx_http_proxy_connect_module#166]
Wanted to know if this module support or in-future going to support use-case where upstream servers are behind proxy?

Setup:

Client/Users -> NGINX -> Squid Proxy -> Upstream.

**Comment by AndreiG6** [comment]
The upstream being behind a reverse proxy makes no difference. Unless you're thinking of utilizing the PROXY protocol, in which case it doesn't make much sense to even use this module.

**Comment by chobits** [comment]
Out of date, if you still have same problem with latest version, you can open a new issue

**Comment by chobits** [comment]
If you wanna CONNECT tunnel to connect your specified squid server, you can use this directive to specify proxied server: `proxy_connect_address`.

See its doc: https://github.com/chobits/ngx_http_proxy_connect_module#proxy_connect_address.

If your case is just proxy normal HTTP/HTTPS request , this module does not affect the nginx proxying logic
