### ISSUE TITLE
openresty-1.17.8.2 prompt :unknown directive "proxy_connect"

### ISSUE THREAD

**Issue by trockxi** [chobits/ngx_http_proxy_connect_module#167]
cd /opt/soft/openresty-1.17.8.2
./configure --prefix=/opt/soft/openresty --with-http_v2_module --with-http_sub_module --with-http_stub_status_module --with-luajit --add-module=/opt/soft/ngx_http_proxy_connect_module
patch -d build/nginx-1.17.8/ -p 1 < /opt/soft/ngx_http_proxy_connect_module/patch/proxy_connect_rewrite_101504.patch

        server {
            listen 8000;
            # dns resolver used by forward proxying
            resolver 223.5.5.5;
            # forward proxy for CONNECT request
            proxy_connect;
            proxy_connect_allow            443 563;
            proxy_connect_connect_timeout  10s;
            proxy_connect_read_timeout     10s;
            proxy_connect_send_timeout     10s;
            # forward proxy for non-CONNECT request
            location / {
                proxy_pass http://$host;
                proxy_set_header Host $host;
            }
         }
2020/11/03 12:10:42 [emerg] 4439#0: unknown directive "proxy_connect" in /opt/soft/openresty/nginx/conf/nginx.conf:424

use patch/proxy_connect_rewrite_1018.patch
The problem is stil
![image](https://user-images.githubusercontent.com/28647418/97950089-b0b53200-1dd0-11eb-8082-1dffcfdfa190.png)

![image](https://user-images.githubusercontent.com/28647418/97949927-18b74880-1dd0-11eb-99c5-035b306bae51.png)

help

**Comment by hehehe886** [comment]
hi u should check "nginx -V"

**Comment by hehehe886** [comment]
> Nginx -V 

if have ngx_http_proxy_connect_module, i recommend change the openresty to stable version. and do it again

**Comment by hehehe886** [comment]
> cd /opt/soft/openresty-1.17.8.2
> ./configure --prefix=/opt/soft/openresty --with-http_v2_module --with-http_sub_module --with-http_stub_status_module --with-luajit --add-module=/opt/soft/ngx_http_proxy_connect_module
> patch -d build/nginx-1.17.8/ -p 1 < /opt/soft/ngx_http_proxy_connect_module/patch/proxy_connect_rewrite_101504.patch
> 
> ```
>     server {
>         listen 8000;
>         # dns resolver used by forward proxying
>         resolver 223.5.5.5;
>         # forward proxy for CONNECT request
>         proxy_connect;
>         proxy_connect_allow            443 563;
>         proxy_connect_connect_timeout  10s;
>         proxy_connect_read_timeout     10s;
>         proxy_connect_send_timeout     10s;
>         # forward proxy for non-CONNECT request
>         location / {
>             proxy_pass http://$host;
>             proxy_set_header Host $host;
>         }
>      }
> ```
> 
> 2020/11/03 12:10:42 [emerg] 4439#0: unknown directive "proxy_connect" in /opt/soft/openresty/nginx/conf/nginx.conf:424
> 
> use patch/proxy_connect_rewrite_1018.patch
> The problem is stil
> ![image](https://user-images.githubusercontent.com/28647418/97950089-b0b53200-1dd0-11eb-8082-1dffcfdfa190.png)
> 
> ![image](https://user-images.githubusercontent.com/28647418/97949927-18b74880-1dd0-11eb-99c5-035b306bae51.png)
> 
> help



> cd /opt/soft/openresty-1.17.8.2
> ./configure --prefix=/opt/soft/openresty --with-http_v2_module --with-http_sub_module --with-http_stub_status_module --with-luajit --add-module=/opt/soft/ngx_http_proxy_connect_module
> patch -d build/nginx-1.17.8/ -p 1 < /opt/soft/ngx_http_proxy_connect_module/patch/proxy_connect_rewrite_101504.patch
> 
> ```
>     server {
>         listen 8000;
>         # dns resolver used by forward proxying
>         resolver 223.5.5.5;
>         # forward proxy for CONNECT request
>         proxy_connect;
>         proxy_connect_allow            443 563;
>         proxy_connect_connect_timeout  10s;
>         proxy_connect_read_timeout     10s;
>         proxy_connect_send_timeout     10s;
>         # forward proxy for non-CONNECT request
>         location / {
>             proxy_pass http://$host;
>             proxy_set_header Host $host;
>         }
>      }
> ```
> 
> 2020/11/03 12:10:42 [emerg] 4439#0: unknown directive "proxy_connect" in /opt/soft/openresty/nginx/conf/nginx.conf:424
> 
> use patch/proxy_connect_rewrite_1018.patch
> The problem is stil
> ![image](https://user-images.githubusercontent.com/28647418/97950089-b0b53200-1dd0-11eb-8082-1dffcfdfa190.png)
> 
> ![image](https://user-images.githubusercontent.com/28647418/97949927-18b74880-1dd0-11eb-99c5-035b306bae51.png)
> 
> help

> Nginx -V

if have ngx_http_proxy_connect_module, i recommend change the openresty to stable version. and do it again

**Comment by chobits** [comment]
Out of date, if you still have same problem with latest version, you can open a new issue
