### ISSUE TITLE
How to send an HTTP CONNECT request from nginx reverse proxy

### ISSUE THREAD

**Issue by abh006** [chobits/ngx_http_proxy_connect_module#176]
I want to send a CONNECT request from my nginx reverse proxy. 
I want to redirect the request coming to my nginx reverse proxy to a remote server through a forward proxy.  How can I do that?

**Comment by chobits** [comment]
If you want to redirect *CONNECT request* to remote server, you should use L4 proxy module, maybe [nginx stream proxy](http://nginx.org/en/docs/stream/ngx_stream_proxy_module.html) worked for you.

* Normal nginx proxy module cannot proxy CONNECT request, it just refused it with 400 status.
* Proxy connect module (this project) cannot proxy CONNECT request, it builds a CONNECT-tunnel with remote server  via tcp connection .
