### ISSUE TITLE
Release project with version number

### ISSUE THREAD

**Issue by soulteary** [chobits/ngx_http_proxy_connect_module#178]
Thank the project members for their contributions, especially @chobits .

I made a docker image for this project, but encountered a problem during the production process. It is difficult for me to find a suitable git hash to fix the code version. https://github.com/soulteary/docker-nginx-forward-proxy

So I had to fork the current project and tag it with the latest hash so that the image build can be carried out on a stable version.

Does the project maintainer consider adding tags when adding patches and modules been updated?

A project with a tag is much more convenient for making reliable container images. The label can be a version number, a change log, or a code name.

**Comment by chobits** [comment]
Hi @soulteary 

For released version and tags , see [this page](https://github.com/chobits/ngx_http_proxy_connect_module/releases).

I have also released a new version v0.0.2 today, see [this link](https://github.com/chobits/ngx_http_proxy_connect_module/releases/tag/v0.0.2). Tag name is `v0.0.2`.

**Comment by soulteary** [comment]
Well done 🎉 , I'll update https://github.com/soulteary/docker-nginx-forward-proxy use the stable version.
