### ISSUE TITLE
安装方法(./configure failure)

### ISSUE THREAD

**Issue by Blue-Skies-firststar** [chobits/ngx_http_proxy_connect_module#18]
$ wget http://nginx.org/download/nginx-1.9.2.tar.gz
$ tar -xzvf nginx-1.9.2.tar.gz
$ cd nginx-1.9.2/
$ patch -p1 < /path/to/ngx_http_proxy_connect_module/proxy_connect.patch
$ ./configure --add-module=/path/to/ngx_http_proxy_connect_module 
安装提示
', needed by `objs/nginx'.  Stop.et `objs/addon/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.o
make[1]: Leaving directory `/root/nginx/nginx-1.12.2'
make: *** [build] Error 2

**Comment by chobits** [comment]
```
$ ./configure --add-module=/path/to/ngx_http_proxy_connect_module
安装提示
', needed by objs/nginx'. Stop.etobjs/addon/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.o
make[1]: Leaving directory `/root/nginx/nginx-1.12.2'
make: *** [build] Error 2
```

这里信息似乎确实，请附完整的`configure`和`make`的输出

**Comment by chobits** [comment]
hi @Blue-Skies-firststar ，你是否还在跟进此问题，如无人回复，24小时候将自动关闭此issue。

**Comment by chobits** [comment]
关闭中，仍有问题可随时打开。
