### ISSUE TITLE
how change http head

### ISSUE THREAD

**Issue by codehater** [chobits/ngx_http_proxy_connect_module#19]
please add command for modify http head like proxy_set_eader

**Comment by chobits** [comment]
hi @codehater 

This module implements HTTP CONNECT tunnel. In this mechanism, the real proxied stream in tunnel is `RAW` tcp stream, so we cannot modified any data of tcp stream.

**Comment by chobits** [comment]
think it resolved, i am closing this issue.

Feel free to reopen if u have any question
