### ISSUE TITLE
How to log real client IP?

### ISSUE THREAD

**Issue by yamarane** [chobits/ngx_http_proxy_connect_module#192]
client --> Nginx:80(proxy connect module: _proxy_connect_address 127.0.0.1:443_)---> Nginx:443--->Application

We can see real client IP at Nginx:80 level but when request came to Nginx:443 level then we can only see 127.0.0.1 as client IP

How to log real client IP?

**Comment by chobits** [comment]
This module cannot support this feature, note that proxy_connect module creates TCP tunnel with backend(`Nginx:443` in your data flow chart. We cannot modify any data proxied in CONNECT tunnel.

**Comment by chobits** [comment]
By the way, if you really want to transfer IP-address, you may modify some code to transfer data in CONNECT` tunnel before proxying any real request and your backend `Nginx:443` also need to be modified to parse this information, which is tricky to implement this feature.
