### ISSUE TITLE
不支持HTTP和FTP协议吗

### ISSUE THREAD

**Issue by mallven** [chobits/ngx_http_proxy_connect_module#20]
HTTPS协议可以正常访问，但是通过HTTP和FTP协议访问的时候报500的错误

**Comment by chobits** [comment]
CONNECT tunnel不区分协议的，在CONNECT请求发送到服务器后建立好隧道后，后续client发过来的任何数据（tcp数据流）都会被服务器直接代理到转发到预期地址。

所以这里是否是HTTP和FTP协议并不重要，但是从实际角度来说，一般只有浏览器会实现CONNECT tunnel，所以应该不会产出FTP的tcp数据流，所以你的使用场景是怎样的？

**Comment by chobits** [comment]
如果是用浏览器的代理功能配置了https和http代理时，https请求是通过CONNECT tunnel来转发的，而http请求则是直接发给被代理的服务器。即 浏览器代理http请求转发到服务器（该模块）时并不会由该模块处理，而是要由nginx的proxy_pass指令和模块来处理

**Comment by mallven** [comment]
谢谢回复，现在已经测试成功了HTTP和HTTPS协议，对于FTP请求 我是不是可以理解为：浏览器配置了代理之后，FTP协议也是直接发送到该模块，但是并不会由该模块吹了，而是nginx安装的ftp模块来处理？谢谢

**Comment by chobits** [comment]
> FTP协议也是直接发送到该模块，但是并不会由该模块吹了，而是nginx安装的ftp模块来处理？谢谢

这个得看你FTP传过来是不是通过http CONNECT tunnel，如果是CONNECT tunnel建立后，后续这个连接上的数据（比如FTP数据）就是由本项目模块代理的。

如果不是走http CONNECT tunnel模式，比如直接ftp协议与nginx交互，则由nginx ftp模块处理（但是原生nginx似乎没有ftp代理模块）

**Comment by chobits** [comment]
Think is resolved, feel free to reopen this issue if u have any problem.
