### ISSUE TITLE
Hunk #3 FAILED at 2075.

### ISSUE THREAD

**Issue by ss891004** [chobits/ngx_http_proxy_connect_module#202]
[root@nginx nginx-1.20.1]# patch -p1 < /usr/local/ngx_http_proxy_connect_module/patch/proxy_connect_rewrite_102101.patch
patching file src/http/ngx_http_core_module.c
patching file src/http/ngx_http_parse.c
Hunk #2 succeeded at 275 (offset -3 lines).
Hunk #3 succeeded at 291 (offset -3 lines).
patching file src/http/ngx_http_request.c
Hunk #1 succeeded at 1116 (offset -2 lines).
Hunk #2 succeeded at 1752 (offset -4 lines).
Hunk #3 FAILED at 2075.
1 out of 3 hunks FAILED -- saving rejects to file src/http/ngx_http_request.c.rej
patching file src/http/ngx_http_request.h
Hunk #1 succeeded at 410 (offset -1 lines).
patching file src/http/ngx_http_variables.c

**Comment by chobits** [comment]
For nginx 1.20.1, you can use proxy_connect_rewrite_1018.patch.

The patch proxy_connect_rewrite_102101.patch file you used is for nginx 1.21.1+



</body>
</html>

**Comment by TaroFang** [comment]
[root@centos7 nginx-1.20.2]# patch -p1 < /usr/local/soft_package/ngx_http_proxy_connect_module-master/patch/proxy_connect_rewrite_102101.patch
patching file src/http/ngx_http_core_module.c
patching file src/http/ngx_http_parse.c
Hunk #2 succeeded at 275 (offset -3 lines).
Hunk #3 succeeded at 291 (offset -3 lines).
patching file src/http/ngx_http_request.c
Hunk #1 succeeded at 1116 (offset -2 lines).
Hunk #2 succeeded at 1752 (offset -4 lines).
Hunk #3 FAILED at 2075.
1 out of 3 hunks FAILED -- saving rejects to file src/http/ngx_http_request.c.rej
patching file src/http/ngx_http_request.h
Hunk #1 succeeded at 410 (offset -1 lines).
patching file src/http/ngx_http_variables.c
