### ISSUE TITLE
nginx: [emerg] unknown directive "proxy_connect"

### ISSUE THREAD

**Issue by MrZ1995** [chobits/ngx_http_proxy_connect_module#206]
![1638263525(1)](https://user-images.githubusercontent.com/29807126/144018537-f327d67d-fc0a-4f21-b88b-76410514e67b.jpg)
This error will be reported when nginx is started after configuration
 tried several versions, but they didn't work. I cried
![1638263651(1)](https://user-images.githubusercontent.com/29807126/144018764-a2f602a9-8a2d-4764-84b9-a060c893e596.jpg)

**Comment by MrZ1995** [comment]
我试了好几个版本了，都没用，哭了

**Comment by MrZ1995** [comment]
![1638263651(1)](https://user-images.githubusercontent.com/29807126/144018764-a2f602a9-8a2d-4764-84b9-a060c893e596.jpg)

**Comment by chobits** [comment]
Not compiled correctly, this module is not compiled into ur nginx. Make sure you compile it one-by-one as install page: https://github.com/chobits/ngx_http_proxy_connect_module#install
