### ISSUE TITLE
winodws nginx 1.21.1 proxy https error

### ISSUE THREAD

**Issue by macoomac** [chobits/ngx_http_proxy_connect_module#208]
### 0. Before Your ASK

1. Try to find an answer by reading a [FAQ](https://github.com/chobits/ngx_http_proxy_connect_module/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aquestion).

### Ⅰ. Issue Description
winodws nginx 1.21.1 proxy https error
build
nginx 1.21.1+proxy_connect_rewrite_102101.patch
 

### Ⅱ. Describe what happened
windows ip : 192.168.1.30

edit d:/nginx/conf/nginx.conf
server {
       resolver 114.114.114.114;
       listen 443;
		ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
		ssl_ciphers         AES128-SHA:AES256-SHA:RC4-SHA:DES-CBC3-SHA:RC4-MD5;
		ssl_certificate     cert.pem;
		ssl_certificate_key cert.key;
		ssl_session_cache   shared:SSL:10m;
		ssl_session_timeout 10m;        
       proxy_connect;
       proxy_connect_allow            443 563;
       proxy_connect_connect_timeout  10s;
       proxy_connect_read_timeout     10s;
       proxy_connect_send_timeout     10s;
    
       location / {
           proxy_pass $scheme://$http_host$request_uri;
			proxy_buffers 256 4k;
			proxy_max_temp_file_size 0;

			proxy_connect_timeout 30s;

			proxy_cache_valid 200 302 10m;
			proxy_cache_valid 301 1h;
			proxy_cache_valid any 1m;

       }
   }
	
server {
 
    resolver 114.114.114.114;
    listen 8008;             
    resolver_timeout 10s;    
    proxy_connect;           
    proxy_connect_allow            443 563; 
    proxy_connect_connect_timeout  10s;     
    proxy_connect_read_timeout     10s;
    proxy_connect_send_timeout     10s;
 
    location / {
        proxy_pass $scheme://$http_host$request_uri;
        proxy_set_header Host $http_host;
        #proxy_pass http://$host;
        #proxy_set_header Host $host;

        proxy_buffers 256 4k;
        proxy_max_temp_file_size 0;
 
        proxy_connect_timeout 30s;

		proxy_cache_valid 200 302 10m;
		proxy_cache_valid 301 1h;
		proxy_cache_valid any 1m;
       

    }
}

start d:/nginx/sbin/nginx.exe   ok!

### Ⅲ. Describe what you expected to happen
other server linux ip: 199.16.20.39

curl curl -v https://mirrors.163.com/debian  -x 192.168.1.30:443
....
* Recv failure: Connection reset by peer
* Received HTTP code 0 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer

export https_proxy="https://192.168.1.30:443"
apt update
...

Err:7 https://mirrors.163.com/debian buster Release
  Could not handshake: An unexpected TLS packet was received. [IP: 192.168.1.30 443]
...

**Comment by chobits** [comment]
answer another similar issue, so close this one

**Comment by 2777484478** [comment]
can  you tell me where is the similar issue?  i have the same question. thanks
