### ISSUE TITLE
nginx日志和Http代理问题 //EN: nginx logging and http proxy problem

### ISSUE THREAD

**Issue by koukoujiang** [chobits/ngx_http_proxy_connect_module#21]
1.为什么nginx日志里的状态码是000？ 难道是因为http connect是4层的，无法解析应用层的http状态码?

2.使用此模块代理Http时，如下网站，会超时，并且日志记录的状态码是404和499 。        但是， 正常应返回tomcat 405页面错误。我用nginx原生的模块代理http请求，可以正常返回tomcat 405错误的页面。为什么呢？
http://onlineuat.cupdata.com:50001/dbesbsit/api/requestEncrypt

**Comment by chobits** [comment]
> 2.使用此模块代理Http时，如下网站，会超时，并且日志记录的状态码是404和499 。 但是， 正常应返回tomcat 405页面错误。我用nginx原生的模块代理http请求，可以正常返回tomcat 405错误的页面。为什么呢？
> http://onlineuat.cupdata.com:50001/dbesbsit/api/requestEncrypt

你是如何代理http请求的（即客户端是什么？客户端是怎样设置代理的？）

**Comment by chobits** [comment]
Think it resolved. Feel free to reopen this issue if u have any problem.
