### ISSUE TITLE
1.19.3  ./configure: error: can not detect sig_atomic_t size on some computers

### ISSUE THREAD

**Issue by GrigoriiTarasov** [chobits/ngx_http_proxy_connect_module#212]
### Ⅰ. Issue Description
On configure step
 ./configure: error: can not detect sig_atomic_t size

### Ⅱ. Describe what happened

./configure --sbin-path=/usr/bin/nginx --conf-path=/etc/nginx/nginx.conf --pid-path=/usr/local/nginx/nginx.pid --error-log-path=/var/log/nginx/nginx_error.log --http-log-path=/var/log/nginx/nginx_access.log --pid-path=/var/run/nginx.pid --with-http_ssl_module --add-module=/tmp/ngx_http_proxy_connect_module

...

 ./configure: error: can not detect sig_atomic_t size

### Ⅲ. Describe what you expected to happen

Successful configure

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

Follow https://github.com/chobits/ngx_http_proxy_connect_module#build-nginx with 1.19.3
On configure step
 ./configure: error: can not detect sig_atomic_t size

### Ⅵ. Environment:

Ubuntu 18.04

**Comment by chobits** [comment]
It may be your local nginx environment. The configure error tell you that it cannot check the size of sig_atomic_t (maybe 4, 8, 16 bytes) in ur environment.

**Comment by chobits** [comment]
think it resolved. feel free to reopen if u still have the same problem
