### ISSUE TITLE
how to process the https's requests before "http_connect_module" forward to the server

### ISSUE THREAD

**Issue by Waterterter** [chobits/ngx_http_proxy_connect_module#215]
i use this module in my website, but i want to filter the host of request before the "http_connect_module" forward requests to the server. so i try to implement this idea in "location /" context, but i find i could not catch the https request.

**Comment by chobits** [comment]
> but i find i could not catch the https request.

Yeah, this is in line with expectations. For CONNECT tunnel protocol, the proxy server ( this module ) cannot parse or change the proxied data flow in TCP tunnel to upstream.  See this faq for the same problem: https://github.com/chobits/ngx_http_proxy_connect_module/wiki/FAQ#can-this-module-parse-and-operate-requests-proxied-in-connect-tunnel

**Comment by chobits** [comment]
think it resolved. feel free to reopen if u still have the same problem
