### ISSUE TITLE
error: duplicate member ‘connect_host

### ISSUE THREAD

**Issue by luo4lu** [chobits/ngx_http_proxy_connect_module#216]
### Ⅰ. Issue Description
This error occurs when the make command is executed,I can use nginx version 1.21.0

### Ⅱ. Describe what happened
![image](https://user-images.githubusercontent.com/27767582/156720131-6f2e7cd9-68cf-488b-91bb-71d95c59301c.png)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅴ. Anything else we need to know?

1. If applicable, add nginx  [debug log](http://nginx.org/en/docs/debugging_log.html).
2.
3.

### Ⅵ. Environment:

1. Tengine/Nginx/OpenResty version (use `sbin/nginx -v`):
2. Which [patch](https://github.com/chobits/ngx_http_proxy_connect_module#select-patch) do you use?

**Comment by chobits** [comment]
I doest not reproduce this problem for nginx-1.21.1.

I guess you patch twice the patch file to nginx source.

You can re-download nginx-1.21.1, and patch it with this patch:  [proxy_connect_rewrite_102101.patch](patch/proxy_connect_rewrite_102101.patch)

**Comment by chobits** [comment]
think it resolved. feel free to reopen if u still have the same problem

**Comment by coolxitech** [comment]
Removing the nginx directory and rebuilding it again will still reproduce this issue.
