### ISSUE TITLE
$upstream_addr not set

### ISSUE THREAD

**Issue by bigboyq** [chobits/ngx_http_proxy_connect_module#217]
### 0. Before Your ASK

1. Try to find an answer by reading a [FAQ](https://github.com/chobits/ngx_http_proxy_connect_module/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aquestion).

### Ⅰ. Issue Description
 log_format main '$proxy_protocol_addr $bytes_sent $request_length [$time_local] "$request" "$upstream_addr"'
		    '$status "$http_referer" "$http_user_agent"' ;

### Ⅱ. Describe what happened
In log file, Upstream_addr expected to be real upstream ip address

### Ⅲ. Describe what you expected to happen
In log file, Upstream_addr was set as -.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅴ. Anything else we need to know?

1. If applicable, add nginx  [debug log](http://nginx.org/en/docs/debugging_log.html).
2.
3.

### Ⅵ. Environment:

1. Tengine/Nginx/OpenResty version (use `sbin/nginx -v`):
2. Which [patch](https://github.com/chobits/ngx_http_proxy_connect_module#select-patch) do you use?

**Comment by chobits** [comment]
Maybe it failed before running 'connecting upstream' phase, you can post the whole log message here to let us check.

**Comment by bigboyq** [comment]
I used $connect_addr instead, but I think $upstream_addr should be reused in connect module too
```  
http {
log_format main '$proxy_protocol_addr $bytes_sent $request_length [$time_local] "$request" "$connect_addr"'
		    '$status "$http_referer" "$http_user_agent"' ;
server{
}
```

**Comment by bigboyq** [comment]
BTW, I wish to log proxy_connect_bind, as I have multi wan, I want to log every outing connections and bind_address
I tried $proxy_connect_bind, but I got 
```
nginx: [emerg] unknown "proxy_connect_bind" variable
nginx: configuration file /etc/nginx/nginx.conf test failed
```
Any ideas?

**Comment by chobits** [comment]
I think its' stale, but mention it anyway, the avaiable variables list is here: https://github.com/chobits/ngx_http_proxy_connect_module?tab=readme-ov-file#variables

And `$proxy_connect_bind` is not in there.
