### ISSUE TITLE
Access restriction to hosts

### ISSUE THREAD

**Issue by disappointed72** [chobits/ngx_http_proxy_connect_module#218]
What is an easy way to allow connections to a whitelist of hosts only?

For example:
allow google.com
allow facebook.com
allow *.blabla.com
and deny connections to any other hosts.

**Comment by chobits** [comment]
You can  check [$connect_host](https://github.com/chobits/ngx_http_proxy_connect_module#connect_host) and [$request_method](https://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_method) variable to block CONNECT request before establishing CONNECT tunnel to upstream.

But you cannot check data flow in established CONNECT tunnel.

**Comment by chobits** [comment]
Maybe as following ( nginx original configuration), have not actually tested it:

if ("$connect_host::$request_method" == "google.com::CONNECT") { # nginx doest not support "and" operation in its if-stmt.
  return 403;
}

Or some lua script to do this, you can check some case:https://github.com/chobits/ngx_http_proxy_connect_module/blob/master/t/http_proxy_connect_lua.t#L89

**Comment by chobits** [comment]
think it resolved. feel free to reopen if u still have the same problem

**Comment by eladitzhakian** [comment]
> What is an easy way to allow connections to a whitelist of hosts only?
> 
> For example: allow google.com allow facebook.com allow *.blabla.com and deny connections to any other hosts.

hey @disappointed72 did you find a solution?
