### ISSUE TITLE
https forward proxy with multiple public source IP

### ISSUE THREAD

**Issue by YuriyTigiev** [chobits/ngx_http_proxy_connect_module#219]
Is it possible to configure nginx with module to work with multiple public source IP? 
For example on a hosted server I have a list of public IP. I would like to configure https "forward proxy" to send any request each time using next IP from the pool. (round-robin algorithm) . Is it technically possible ?

**Comment by chobits** [comment]
If you wanna to self-control upstream ip address, you can use [$proxy_connect_address directive](https://github.com/chobits/ngx_http_proxy_connect_module#proxy_connect_address). The controlling logic can be implemented via lua or nginx configuration. 

This test case( via lua) may be helpful: https://github.com/chobits/ngx_http_proxy_connect_module/blob/master/t/http_proxy_connect.t#L113

**Comment by chobits** [comment]
Think it resolved. Feel free to reopen it if you still have same issue. 
Open a new issue if you have any other problem.
