### ISSUE TITLE
Can it used as a https proxy to tunnel tcp?

### ISSUE THREAD

**Issue by friskfly** [chobits/ngx_http_proxy_connect_module#22]
I tried in ssl server block , but not succeed

**Comment by chobits** [comment]
hi, this module is used to handle CONNECT-request tunnel, this request is plain request (not over ssl).  Seems that there is no client (webbrowsers / curl )  sending CONNECT request over SSL layer. 

So if u want to use this module, config it in non-ssl server.

For more details of CONNECT tunnel, see: https://en.wikipedia.org/wiki/HTTP_tunnel#HTTP_CONNECT_tunneling

**Comment by friskfly** [comment]
Chrome and Firefox has htttps proxy support.  other web client can use nghttpx to translate http to h2 ,   I'm now use nghttpx as frontend  server,  and nginx with this module in backend .  this is workaround way.   If the moudle can directly support CONNECT request over ssl , i can just use nginx  😀.      see this blog https://wzyboy.im/post/1052.html

**Comment by chobits** [comment]
Thanks for sharing this idea, let me look deep into it this weekend:)

**Comment by chobits** [comment]
hi @friskfly , I have made connect tunnel over ssl work. I'm currenty using chrome-https-proxy-setting with ngx_http_proxy_connect_module to write this comment :)

---

Here is my ngx_http_proxy_connect_module configure:

```
    server {
        listen       8443 ssl;

        server_name  localhost;

        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers         AES128-SHA:AES256-SHA:RC4-SHA:DES-CBC3-SHA:RC4-MD5;
        ssl_certificate     /Users/xiaochen/work/nginx/cert.pem;
        ssl_certificate_key /Users/xiaochen/work/nginx/cert.key;
        ssl_session_cache   shared:SSL:10m;
        ssl_session_timeout 10m;

        resolver 8.8.8.8;

        ### connect tunnel
        proxy_connect;
        proxy_connect_allow            443 563;
        proxy_connect_connect_timeout  10s;
        proxy_connect_read_timeout     10s;
        proxy_connect_send_timeout     10s;

        location / {
            proxy_set_header Host $host;
            proxy_pass http://$host;
        }
    }
```

---

Here is my chrome https proxy setting (note that I use SwitchyOmega extension)

![image](https://user-images.githubusercontent.com/623062/33230829-7c54f238-d225-11e7-8ea8-124cfe84cd20.png)

---

The main problem, I try to resolve is, chrome reporting error: ERR_PROXY_CERTIFICATE_INVALID.
If you have the same problem, I can show how to fix. 

Note that I'm using macOS Sierra(version 10.12.6) and Goolge Chrome (Version 62.0.3202.94 (Official Build) (64-bit)).

1. use the following script to generate SSL certificate & key.

```
$ cat genkey.sh
#!/bin/bash

openssl req \
  -newkey rsa:2048 \
  -x509 \
  -nodes \
  -keyout cert.key \
  -new \
  -out cert.pem \
  -subj /CN=localhost \
  -reqexts SAN \
  -extensions SAN \
  -config <(cat /System/Library/OpenSSL/openssl.cnf \
       <(printf '[SAN]\nsubjectAltName=DNS:localhost')) \
  -sha256 \
  -days 3650
$ ./genkey.sh
$ ls
cert.key   cert.pem
```

2. install generated certificate `cert.pem` as a trusted root certificate on macOS:

```
1 Open Keychain Access
2 Choose "System" in the "Keychains" list
3 Choose "Certificates" in the "Category" list
4 Choose "File | Import Items..."
 Browse to the file created above, "cert.pem", select it, and click "Open"
 Select your newly imported certificate in the "Certificates" list.
5. Click the "i" button, or right click on your certificate, and choose "Get Info"
 Expand the "Trust" option
 Change "When using this certificate" to "Always Trust"
 Close the dialog, and you'll be prompted for your password.
```

For more details, see https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate.

Here is my configure screenshot:

![image](https://user-images.githubusercontent.com/623062/33231045-3c7c8352-d229-11e7-9fd8-f3a49f29ec32.png)

**Comment by friskfly** [comment]
@chobits I tried again , with `listen 443 ssl ` is ok ,  but when I configure with `listen 443 ssl http2;`   ,chrome shows tunnel failed

**Comment by chobits** [comment]
hi @friskfly 

Yes, this is known issue in my TODO-list. 

This is a long term plan, I dont have time to deal with this currently.
---

At least three points we should focus:

1. This module only patches HTTP status line parsing function for  parsing CONNECT method.
HTTP2 module has its own parsing function, which is not patched by this module.
2. how to notify client that this module has established tunnel (maybe return 200 establish, not sure)
3. how to upgrade client HTTP2 connection to TCP stream tunnel (maybe upgrade one HTTP stream not the whole connection, not sure)

**Comment by friskfly** [comment]
I see.  Thx for your reply.

**Comment by chobits** [comment]
I am closing this issue, the TODO issue for h2 is added, see https://github.com/chobits/ngx_http_proxy_connect_module/issues/25.

**Comment by chaoqing** [comment]
Hi, I am building a https proxy to block the ads working with PAC. The idea is all `https://ads.domain/any/uri` will be forward proxy to nginx server and it always return `empty_gif` or status 204. But after I configure my nginx default.conf as follow, `https_proxy=my.server:8080 curl https://www.baidu.com` still return the original webpage.

```
    server {
        listen       8080 ssl;

        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers         AES128-SHA:AES256-SHA:RC4-SHA:DES-CBC3-SHA:RC4-MD5;
        ssl_certificate     /my/nginx/cert.pem;
        ssl_certificate_key /myk/nginx/cert.key;
        ssl_session_cache   shared:SSL:10m;
        ssl_session_timeout 10m;

        resolver 8.8.8.8;

        ### connect tunnel
        proxy_connect;
        proxy_connect_allow            443 563;
        proxy_connect_connect_timeout  10s;
        proxy_connect_read_timeout     10s;
        proxy_connect_send_timeout     10s;

        location / {
            empty_gif;
        }
    }
```

Please help me with this.

**Comment by tomoncle** [comment]
# 无法启用 ssl
* nginx : 1.16.1
* OS:   centos7
* nginx info:  
```bash
nginx version: nginx/1.16.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_perl_module=dynamic --with-threads --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-stream_realip_module --with-stream_geoip_module=dynamic --with-http_slice_module --with-mail --with-mail_ssl_module --with-compat --with-file-aio --with-http_v2_module --add-dynamic-module=/home/tomoncle/ngx_http_proxy_connect_module
```
## 正向代理配置
```bash
server {
    listen                         6443 ssl;

    ssl_protocols                  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers                    AES128-SHA:AES256-SHA:RC4-SHA:DES-CBC3-SHA:RC4-MD5;
    ssl_certificate                /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key            /etc/nginx/ssl/nginx.key;
    ssl_session_cache              shared:SSL:10m;
    ssl_session_timeout            10m;

    resolver 114.114.114.114;

    ### connect tunnel
    proxy_connect;
    proxy_connect_allow            443 563;
    proxy_connect_connect_timeout  10s;
    proxy_connect_read_timeout     10s;
    proxy_connect_send_timeout     10s;

    location / {
        proxy_set_header           Host $host;
        proxy_pass                 http://$host;
    }
}
```
## 测试
```bash
[root@5c5b6 ~]# curl -x 127.0.0.1:6443 -v www.baidu.com
* About to connect() to proxy 127.0.0.1 port 6443 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 6443 (#0)
> GET HTTP://www.baidu.com/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: www.baidu.com
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 400 Bad Request
< Server: nginx/1.16.1
< Date: Thu, 23 Dec 2021 01:46:48 GMT
< Content-Type: text/html; charset=utf-8,gbk
< Content-Length: 255
< Connection: close
< 
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx/1.16.1</center>
</body>
</html>
* Closing connection 0
[root@5c5b6 ~]# curl -x 127.0.0.1:6443 -v https://www.baidu.com
* About to connect() to proxy 127.0.0.1 port 6443 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 6443 (#0)
* Establish HTTP proxy tunnel to www.baidu.com:443
> CONNECT www.baidu.com:443 HTTP/1.1
> Host: www.baidu.com:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 400 Bad Request
< Server: nginx/1.16.1
< Date: Thu, 23 Dec 2021 01:46:54 GMT
< Content-Type: text/html; charset=utf-8,gbk
< Content-Length: 255
< Connection: close
< 
* Received HTTP code 400 from proxy after CONNECT
* Connection #0 to host 127.0.0.1 left intact
curl: (56) Received HTTP code 400 from proxy after CONNECT
````
## 问题
 当我**关闭**ssl 时（配置文件第一行删除ssl参数）代理工作正常
 当我**启用**ssl时（如上配置）出现以上的测试问题

 我看您这边配置成功了，是可以支持  客户端 -> `HTTPS` -> 代理服务 -> `HTTP/HTTPS` -> 目标服务器 , 
 但是我不知道问题出在哪里，能否给出一些意见。谢谢

**Comment by patrickkon** [comment]
I have the same problem 

> # 无法启用 ssl
> * nginx : 1.16.1
> * OS:   centos7
> * nginx info:
> 
> ```shell
> nginx version: nginx/1.16.1
> built by gcc 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 
> built with OpenSSL 1.0.2k-fips  26 Jan 2017
> TLS SNI support enabled
> configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_perl_module=dynamic --with-threads --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-stream_realip_module --with-stream_geoip_module=dynamic --with-http_slice_module --with-mail --with-mail_ssl_module --with-compat --with-file-aio --with-http_v2_module --add-dynamic-module=/home/tomoncle/ngx_http_proxy_connect_module
> ```
> 
> ## 正向代理配置
> ```shell
> server {
>     listen                         6443 ssl;
> 
>     ssl_protocols                  TLSv1 TLSv1.1 TLSv1.2;
>     ssl_ciphers                    AES128-SHA:AES256-SHA:RC4-SHA:DES-CBC3-SHA:RC4-MD5;
>     ssl_certificate                /etc/nginx/ssl/nginx.crt;
>     ssl_certificate_key            /etc/nginx/ssl/nginx.key;
>     ssl_session_cache              shared:SSL:10m;
>     ssl_session_timeout            10m;
> 
>     resolver 114.114.114.114;
> 
>     ### connect tunnel
>     proxy_connect;
>     proxy_connect_allow            443 563;
>     proxy_connect_connect_timeout  10s;
>     proxy_connect_read_timeout     10s;
>     proxy_connect_send_timeout     10s;
> 
>     location / {
>         proxy_set_header           Host $host;
>         proxy_pass                 http://$host;
>     }
> }
> ```
> 
> ## 测试
> ```shell
> [root@5c5b6 ~]# curl -x 127.0.0.1:6443 -v www.baidu.com
> * About to connect() to proxy 127.0.0.1 port 6443 (#0)
> *   Trying 127.0.0.1...
> * Connected to 127.0.0.1 (127.0.0.1) port 6443 (#0)
> > GET HTTP://www.baidu.com/ HTTP/1.1
> > User-Agent: curl/7.29.0
> > Host: www.baidu.com
> > Accept: */*
> > Proxy-Connection: Keep-Alive
> > 
> < HTTP/1.1 400 Bad Request
> < Server: nginx/1.16.1
> < Date: Thu, 23 Dec 2021 01:46:48 GMT
> < Content-Type: text/html; charset=utf-8,gbk
> < Content-Length: 255
> < Connection: close
> < 
> <html>
> <head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
> <body>
> <center><h1>400 Bad Request</h1></center>
> <center>The plain HTTP request was sent to HTTPS port</center>
> <hr><center>nginx/1.16.1</center>
> </body>
> </html>
> * Closing connection 0
> [root@5c5b6 ~]# curl -x 127.0.0.1:6443 -v https://www.baidu.com
> * About to connect() to proxy 127.0.0.1 port 6443 (#0)
> *   Trying 127.0.0.1...
> * Connected to 127.0.0.1 (127.0.0.1) port 6443 (#0)
> * Establish HTTP proxy tunnel to www.baidu.com:443
> > CONNECT www.baidu.com:443 HTTP/1.1
> > Host: www.baidu.com:443
> > User-Agent: curl/7.29.0
> > Proxy-Connection: Keep-Alive
> > 
> < HTTP/1.1 400 Bad Request
> < Server: nginx/1.16.1
> < Date: Thu, 23 Dec 2021 01:46:54 GMT
> < Content-Type: text/html; charset=utf-8,gbk
> < Content-Length: 255
> < Connection: close
> < 
> * Received HTTP code 400 from proxy after CONNECT
> * Connection #0 to host 127.0.0.1 left intact
> curl: (56) Received HTTP code 400 from proxy after CONNECT
> ```
> 
> ## 问题
> 当我**关闭**ssl 时（配置文件第一行删除ssl参数）代理工作正常 当我**启用**ssl时（如上配置）出现以上的测试问题
> 
> 我看您这边配置成功了，是可以支持 客户端 -> `HTTPS` -> 代理服务 -> `HTTP/HTTPS` -> 目标服务器 , 但是我不知道问题出在哪里，能否给出一些意见。谢谢

I have the same problem too. "client sent plain HTTP request to HTTPS port while reading client request headers,"

**Comment by chobits** [comment]
> I have the same problem
> 
> > # 无法启用 ssl
> > ....
> > ## 问题
> > 当我**关闭**ssl 时（配置文件第一行删除ssl参数）代理工作正常 当我**启用**ssl时（如上配置）出现以上的测试问题
> > 我看您这边配置成功了，是可以支持 客户端 -> `HTTPS` -> 代理服务 -> `HTTP/HTTPS` -> 目标服务器 , 但是我不知道问题出在哪里，能否给出一些意见。谢谢
> 
> I have the same problem too. "client sent plain HTTP request to HTTPS port while reading client request headers,"

hi, your configuration is right, but ur constructed curl command is not right, see my latest documentation here: https://github.com/chobits/ngx_http_proxy_connect_module#example-for-curl-connect-request-in-https

![image](https://user-images.githubusercontent.com/623062/223040185-261b5161-5e23-448e-8413-77b76d92361a.png)

**Comment by ns-aparnau** [comment]
Hello, I am kind of stuck on this error! Can you please point out if I am missing something here -
I am trying to use nginx to serve a https proxy request  but i am getting 400
curl -x 172.18.29.108:443 https://dl.boxcloud.com/d/1/21bytes.txt/download -v
*   Trying 172.18.29.108:443...
* TCP_NODELAY set
* Connected to 172.18.29.108 (172.18.29.108) port 443 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to dl.boxcloud.com:443
> CONNECT dl.boxcloud.com:443 HTTP/1.1
> Host: dl.boxcloud.com:443
> User-Agent: curl/7.68.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 400 Bad Request
< Server: nginx/1.25.0
< Date: Fri, 16 Jun 2023 12:09:47 GMT
< Content-Type: text/html
< Content-Length: 255
< Connection: close
<
* Received HTTP code 400 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Received HTTP code 400 from proxy after CONNECT 

Error :  "CONNECT dl.boxcloud.com:443 HTTP/1.1" 400 255 "-" "curl/7.68.0" 0.000 - .

Same request to port 80 (http request) is successful. 
curl -x 172.18.29.108:80 http://dl.boxcloud.com/d/1/21bytes.txt/download -v
"GET http://dl.boxcloud.com/d/1/21bytes.txt/download HTTP/1.1" 200 20 "-" "curl/7.68.0" 0.002 0.001 .

Here is my nginx configuration-

server {

  sendfile on;
  tcp_nopush off;
  output_buffers 1 4096k;
  keepalive_timeout 65;
  tcp_nodelay on;

  listen 443 ssl;

  ssl_certificate /etc/nginx/certs/box/box.pem;
  ssl_certificate_key /etc/nginx/certs/box/box.key;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

  server_name dl.boxcloud.com;

  allow all;

  proxy_connect;
  proxy_connect_allow 443;
  proxy_connect_connect_timeout  10s;
  proxy_connect_data_timeout     10s;

  client_max_body_size 2G;
  client_body_buffer_size 32k;

  resolver 192.168.80.11;

  proxy_read_timeout 1000;
  proxy_http_version 1.1;
  proxy_set_header Connection "";
  proxy_buffer_size 4096k;
  proxy_buffers 8 4096k;
  large_client_header_buffers 4 16k;
  proxy_busy_buffers_size 4096k;
  #proxy_buffering off;


  location ~ ^/d/1/[0-9a-z]+/download$ {

    proxy_pass http://box_download;
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
    proxy_set_header Host $host;
    proxy_ssl_server_name on;
  }

  location / {


    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host  $host;
    proxy_set_header X-NginX-Proxy true;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_cache cache;

    add_header X-Proxy-Cache $upstream_cache_status;
    proxy_pass http://box_download;
    proxy_ssl_server_name on;
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
    proxy_redirect off;

  }
}
