### ISSUE TITLE
Set an upstream forward proxy

### ISSUE THREAD

**Issue by DUOLabs333** [chobits/ngx_http_proxy_connect_module#220]
## Why you need it?

I have a mitmproxy on port 2222, and I want to move it behind nginx, running it on `https://proxy.tld`, so that `curl -x proxy.tld:80 neverssl.com` and `curl -x proxy.tld:80 https://google.com` both send requests to `localhost:2222`

**Comment by chobits** [comment]
If you wanna to self-control upstream ip address, you can use [$proxy_connect_address directive](https://github.com/chobits/ngx_http_proxy_connect_module#proxy_connect_address). The controlling logic can be implemented via lua or nginx configuration. 

This test case( via lua) may be helpful: https://github.com/chobits/ngx_http_proxy_connect_module/blob/master/t/http_proxy_connect.t#L113

**Comment by chobits** [comment]
Hi, this module is not tested under windows.

If you want to use it under windows, you may debug it with debug-log by your self.
Enable debug log to see what happened :http://nginx.org/en/docs/debugging_log.html
