### ISSUE TITLE
patch: **** Only garbage was found in the patch input

### ISSUE THREAD

**Issue by wangquansh** [chobits/ngx_http_proxy_connect_module#222]
patch -p1 < proxy_connect_rewrite_1018.patch 
patch: **** Only garbage was found in the patch input.

GNU patch 2.7.1

-----------
CentOS Linux release 7.9.2009

nginx-1.20.1

./configure --add-module=ngx_http_proxy_connect_module

adding module in ngx_http_proxy_connect_module
./configure: error: no ngx_http_proxy_connect_module/config was found

**Comment by FabienOnGithub** [comment]
Check if your file is the same as the [original](https://github.com/chobits/ngx_http_proxy_connect_module/blob/master/patch/proxy_connect_rewrite_1018.patch).
I had this error when i did wget "url/to/the/patch" because it downloaded the html page and not the file...

**Comment by Hightmar** [comment]
Download patch with 
`wget https://raw.githubusercontent.com/chobits/ngx_http_proxy_connect_module/master/patch/proxy_connect_rewrite_1018.patch`

I bet you downloaded the web page and not the code

**Comment by chobits** [comment]
Also note that all patch files have been included in `patch/` directory of this module. 

```
DESKTOP-CQEO1JN work $ cd ./ngx_http_proxy_connect_module/
DESKTOP-CQEO1JN ngx_http_proxy_connect_module $ ls patch/
proxy_connect_1014.patch  proxy_connect_rewrite_1014.patch    proxy_connect_rewrite_1015.patch  proxy_connect_rewrite_102101.patch
proxy_connect.patch       proxy_connect_rewrite_101504.patch  proxy_connect_rewrite_1018.patch  proxy_connect_rewrite.patch
```

> Check if your file is the same as the [original](https://github.com/chobits/ngx_http_proxy_connect_module/blob/master/patch/proxy_connect_rewrite_1018.patch). I had this error when i did wget "url/to/the/patch" because it downloaded the html page and not the file...

**Comment by henry5001** [comment]
Haha, it's really strange to visit this link, and you can't notice it without changing the operating system

https://github.com/chobits/ngx_http_proxy_connect_module/blob/master/patch/proxy_connect_rewrite_102101.patch
- linux -> proxy_connect_rewrite_102101.patch -> non-proxy_connect_rewrite_102101.patch  (patch: **** Only garbage was found in the patch input.)
- windows -> proxy_connect_rewrite_102101.html

It's weird, so, I chose to use git clone
