### ISSUE TITLE
Can i get upstream first byte time?

### ISSUE THREAD

**Issue by cristianleez** [chobits/ngx_http_proxy_connect_module#226]
Just like the stream module, embedded variable $upstream_first_byte_time?
![image](https://user-images.githubusercontent.com/17487268/180347011-a0c5738a-9964-4b7b-848e-0cd092b99391.png)

If not, can this feature be supported?

**Comment by chobits** [comment]
Currenty this variable not work for proxy_connect module.

> If not, can this feature be supported?

Yeah, we can add new variable `$proxy_connect_first_byte_time` similar to stream module.

**Comment by cristianleez** [comment]
这是来自QQ邮箱的自动回复邮件，邮件已收到。                                                      李震

**Comment by chobits** [comment]
See this pr: https://github.com/chobits/ngx_http_proxy_connect_module/pull/228

**Comment by cristianleez** [comment]
Ok,thank you.

**Comment by chobits** [comment]
pr has been merged into master.

You can check $proxy_connect_first_byte_time doc: https://github.com/chobits/ngx_http_proxy_connect_module#proxy_connect_first_byte_time

**Comment by chobits** [comment]
new version has been released with this issue resolved

**Comment by cristianleez** [comment]
这是来自QQ邮箱的自动回复邮件，邮件已收到。                                                      李震
