### ISSUE TITLE
Nginx1.22.0 compile error

### ISSUE THREAD

**Issue by likun0121** [chobits/ngx_http_proxy_connect_module#229]
I compiled Nginx-1.22.0, then I receive this error message:
![image](https://user-images.githubusercontent.com/23078367/182131437-755adbb5-e281-49de-80b2-5021f0c5822d.png)

![image](https://user-images.githubusercontent.com/23078367/182130783-9c859af1-84dd-4592-a0d8-f3a9ee3c1804.png)
I'm not sure what caused the problem, did I handled it in wrong way?

**Comment by chobits** [comment]
This problem is caused by wrong patch you used.
Select right patch from this doc:https://github.com/chobits/ngx_http_proxy_connect_module#select-patch

[proxy_connect_rewrite_102101.patch

**Comment by likun0121** [comment]
Thanks, it worked! i remember i tried to select right version patch, but it doesn't word, this time, i remove nginx source file and decompressed nginx.tar again, it worked.
