### ISSUE TITLE
Unable to restrict the domain name of forward proxy

### ISSUE THREAD

**Issue by xxscloud5722** [chobits/ngx_http_proxy_connect_module#230]
### 0. Before Your ASK

1. Try to find an answer by reading a [FAQ](https://github.com/chobits/ngx_http_proxy_connect_module/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aquestion).

### Ⅰ. Issue Description
    server {

       listen 3002;
       server_name sms.tencentcloudapi.com;

       # dns resolver used by forward proxying
       resolver 8.8.8.8;

       # forward proxy for CONNECT request
       proxy_connect;
       proxy_connect_allow 443 80;
       proxy_connect_connect_timeout 10s;
       proxy_connect_read_timeout 10s;
       proxy_connect_send_timeout 10s;

       # forward proxy for non-CONNECT request
       location / {
           proxy_pass $scheme://sms.tencentcloudapi.com$request_uri;
           # proxy_set_header Host sms.tencentcloudapi.com;
       }
    }

### Ⅲ. Describe what you expected to happen

Proxies can be restricted normally

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### V. Anything else we need to know?

None

### VI. Environment:

Nginx 1.19.2

**Comment by chobits** [comment]
> Proxies can be restricted normally

It is as expected that proxied data  cannot be restricted via domain name. Note that we have no method to parse the proxied data in CONNECT tunnel.

Many people have asked why or how to parse, hijack, and intercept proxy data. This is practically impossible to achieve.
Because the proxied data can theoretically be in any forml; in fact, the vast majority of data is ssl encrypted.

**Comment by chobits** [comment]
The only data you can parse is the CONNECT request before the CONNECT tunnel is established.

You can check this request as following( note that I dont test the script, just for reference.

```

set $found "";

if ($request_method = "CONNECT") {
  set $found "1"
}

if ($connect_host = "xx.com") {
   set $found "2";
}

if ($found = "12") {
   return 403;
}

```

**Comment by jingjingxyk** [comment]
# nginx 服务器只允许特定地址访问
map $host $tls_proxy_allow_url_flag {
       default 0;
       ~^([\w|-]+?)\.googlesource\.com$ 1;
       ~^([\w|-]+?)\.googleapis\.com$ 1;
       ~^chrome-infra-packages\.appspot\.com$ 1;
}

# 例子
server {

    if ( $tls_proxy_allow_url_flag != 1) {
          return 403 '{"status":"403","result":"no allow","message":"403"}';
    }

}

**Comment by chobits** [comment]
Think it resolved. Feel free to reopen it if you still have same issue. 
Open a new issue if you have any other problem.
