### ISSUE TITLE
report bug:src/http/ngx_http_request.h:47: error: "NGX_HTTP_CONNECT" redefined [-Werror],when excute "make".In nginx 1.23.1

### ISSUE THREAD

**Issue by L2421800049** [chobits/ngx_http_proxy_connect_module#231]
src/http/ngx_http_request.h:47: error: "NGX_HTTP_CONNECT" redefined [-Werror],when excute "make".In nginx 1.23.1.

logs:

In file included from src/http/ngx_http.h:32,
                 from src/http/ngx_http.c:10:
src/http/ngx_http_request.h:47: error: "NGX_HTTP_CONNECT" redefined [-Werror]
 #define NGX_HTTP_CONNECT                   0x10000
 
src/http/ngx_http_request.h:44: note: this is the location of the previous definition
 #define NGX_HTTP_CONNECT                   0x00010000
 
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:922: objs/src/http/ngx_http.o] Error 1
make[1]: Leaving directory '/opt/nginx'
make: *** [Makefile:10: build] Error 2

**Comment by chobits** [comment]
which patch do you use?

This problem is caused by old patch you used, which defined NGX_HTTP_CONNECT macro while your new nginx has this macro in nginx core sourse already.

Select right patch from this doc:https://github.com/chobits/ngx_http_proxy_connect_module#select-patch

**Comment by chobits** [comment]
all patch files has been included in `patch/` directory of this module.
