### ISSUE TITLE
Unable to run make with nginx-1.23.2

### ISSUE THREAD

**Issue by modosm** [chobits/ngx_http_proxy_connect_module#245]
Dear Team,

I am using an Ubuntu machine to  compile the module and get a strange error at line  1502 
Can you please advise how to proceed?

https://github.com/chobits/ngx_http_proxy_connect_module/blob/3930c7e43895ed6578845d9a31f400b949914a67/ngx_http_proxy_connect_module.c#L1502

make
make -f objs/Makefile
make[1]: Entering directory '/home/user/nginx/nginx-1.23.2'
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules \
	-o objs/addon/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.o \
	../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c
../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c: In function 'ngx_http_proxy_connect_handler':
../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1502:30: error: 'ngx_http_request_t' {aka 'struct ngx_http_request_s'} has no member named 'connect_host'; did you mean 'connection'?
 1502 |             url.url.len = r->connect_host.len;
      |                              ^~~~~~~~~~~~
      |                              connection
../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1503:31: error: 'ngx_http_request_t' {aka 'struct ngx_http_request_s'} has no member named 'connect_host'; did you mean 'connection'?
 1503 |             url.url.data = r->connect_host.data;
      |                               ^~~~~~~~~~~~
      |                               connection
../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1507:26: error: 'ngx_http_request_t' {aka 'struct ngx_http_request_s'} has no member named 'connect_host'; did you mean 'connection'?
 1507 |         url.url.len = r->connect_host.len;
      |                          ^~~~~~~~~~~~
      |                          connection
../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1508:27: error: 'ngx_http_request_t' {aka 'struct ngx_http_request_s'} has no member named 'connect_host'; did you mean 'connection'?
 1508 |         url.url.data = r->connect_host.data;
      |                           ^~~~~~~~~~~~
      |                           connection
../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1511:27: error: 'ngx_http_request_t' {aka 'struct ngx_http_request_s'} has no member named 'connect_port_n'; did you mean 'connection'?
 1511 |     url.default_port = r->connect_port_n;
      |                           ^~~~~~~~~~~~~~
      |                           connection
../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1556:55: error: 'ngx_http_request_t' {aka 'struct ngx_http_request_s'} has no member named 'connect_port_n'; did you mean 'connection'?
 1556 |     u->resolved->port = (in_port_t) (url.no_port ? r->connect_port_n : url.port);
      |                                                       ^~~~~~~~~~~~~~
      |                                                       connection
In file included from src/core/ngx_core.h:60,
                 from ../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:7:
../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1592:27: error: 'ngx_http_request_t' {aka 'struct ngx_http_request_s'} has no member named 'connect_host'; did you mean 'connection'?
 1592 |                       &r->connect_host);
      |                           ^~~~~~~~~~~~
src/core/ngx_log.h:86:67: note: in definition of macro 'ngx_log_error'
   86 |     if ((log)->log_level >= level) ngx_log_error_core(level, log, __VA_ARGS__)
      |                                                                   ^~~~~~~~~~~
../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c: In function 'ngx_http_proxy_connect_allow_handler':
../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1668:41: error: 'ngx_http_request_t' {aka 'struct ngx_http_request_s'} has no member named 'connect_port_n'; did you mean 'connection'?
 1668 |             if ((ports[i][1] == 0 && r->connect_port_n == ports[i][0])
      |                                         ^~~~~~~~~~~~~~
      |                                         connection
../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1669:39: error: 'ngx_http_request_t' {aka 'struct ngx_http_request_s'} has no member named 'connect_port_n'; did you mean 'connection'?
 1669 |                 || (ports[i][0] <= r->connect_port_n && r->connect_port_n <= ports[i][1]))
      |                                       ^~~~~~~~~~~~~~
      |                                       connection
../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1669:60: error: 'ngx_http_request_t' {aka 'struct ngx_http_request_s'} has no member named 'connect_port_n'; did you mean 'connection'?
 1669 |                 || (ports[i][0] <= r->connect_port_n && r->connect_port_n <= ports[i][1]))
      |                                                            ^~~~~~~~~~~~~~
      |                                                            connection
../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1677:16: error: 'ngx_http_request_t' {aka 'struct ngx_http_request_s'} has no member named 'connect_port_n'; did you mean 'connection'?
 1677 |         if (r->connect_port_n == 443 || r->connect_port_n == 563) {
      |                ^~~~~~~~~~~~~~
      |                connection
../ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1677:44: error: 'ngx_http_request_t' {aka 'struct ngx_http_request_s'} has no member named 'connect_port_n'; did you mean 'connection'?
 1677 |         if (r->connect_port_n == 443 || r->connect_port_n == 563) {
      |                                            ^~~~~~~~~~~~~~
      |                                            connection
make[1]: *** [objs/Makefile:1204: objs/addon/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.o] Error 1
make[1]: Leaving directory '/home/user/nginx/nginx-1.23.2'
make: *** [Makefile:10: build] Error 2

**Comment by modosm** [comment]
Tested with previous version. nginx-1.22.1 works fine.

**Comment by chobits** [comment]
The compilation error from your issue means that the proxy connect patch had not been patched, so there is no connect_host field in r structure. 

> ngx_http_request_s'} has no member named 'connect_host'; did you mean 'connection'?
> 1502 | url.url.len = r->connect_host.len;


Did you forget to patch on nginx-1.23.2?

**Comment by chobits** [comment]
I got same compilation error when I compiled 1.23.2 without the patch .
If I patched it, then it worked and passed t/ test cases.

**Comment by chobits** [comment]
Im closing this issue, feel free to reopen if u still have .
