### ISSUE TITLE
does Proxy-Authentication header can only be sent when sending request wth CURL?

### ISSUE THREAD

**Issue by brooklyn097** [chobits/ngx_http_proxy_connect_module#254]
Hello,

I'm doing follow https://github.com/chobits/ngx_http_proxy_connect_module/issues/42#issuecomment-502985437 to authenticate for requests using Lua.
It works fine when I send request using CURL

`curl https://ipinfo.io/json -x localhost:3318  --proxy-user hello:world`

I can get Proxy-Authentication header from above request (using `ngx.var.http_proxy_authorization`)

But when I use browser's extensions such as FoxyProxy, SwitchyOmega. I can't get the Proxy-Authentication header anymore for both http and https requests. It seems like it wasn't sending by the proxy extension or something else.

Please help me to clarify this.

**Comment by chobits** [comment]
You may need to figure out whether or how browser's extensions such as SwitchyOmega  handles the “HTTP Basic Authentication” protocol, which is beyond my experience. Or maybe it does not support, see here: https://github.com/FelisCatus/SwitchyOmega/issues/1472#issuecomment-396011929


In this https://github.com/chobits/ngx_http_proxy_connect_module/issues/42#issuecomment-502985437, we already knew how client ( `curl` or `proxytunnel` ) handled auth basic protocol, so we could resolve it easily.

**Comment by brooklyn097** [comment]
> 

Oh I see. Thank you for pointing this out.
