### ISSUE TITLE
請問如何在proxy_connect_address增加多筆domain?

### ISSUE THREAD

**Issue by PenChien** [chobits/ngx_http_proxy_connect_module#257]
但我想要增加白名單去控管Proxy連線資源
比如只允許Proxy連到google.com, youtube.com, github.com
但我設定多筆的時候會出現錯誤，設一筆紀錄是成功的
想問要如何設定多筆?

謝謝

**Comment by chobits** [comment]
From doc:

> NOTE: If using set $<nginx variable> and proxy_connect_address $<nginx variable> together, you should use proxy_connect_rewrite.patch instead, see [Install](https://github.com/chobits/ngx_http_proxy_connect_module#install) for more details.

你可以配置一個nginx變量。然後通過lua來做邏輯來選擇控制後端代理到的服務器的地址。不過你的需求用這個指令不是很適合。這個指令是用來强制指定後端地址的。

如果你想對代理鏈接的後端地址（域名）做訪問控制，可以 直接通過lua在CONNECT請求進入的時候檢測期望代理到的後端地址或者域名（$connect_host變量)來判斷是否允許代理。

類似代碼如下（為經過測試，只是提供大概思路，可自行調試）

* nginx.conf中插入

```
rewrite_by_lua_file check_connect_host.lua;
```

* check_connect_host.lua

```
if ngx.var.request_method ~= "CONNECT" then
  return
end

-- your custom access control logic
if ngx.var.connect_host ~= "google.com" then
   ngx.exit(403)
end
```

**Comment by PenChien** [comment]
感謝大神回覆，我簡單測試了一下可以
