### ISSUE TITLE
error when do 'make'

### ISSUE THREAD

**Issue by bangzhuX** [chobits/ngx_http_proxy_connect_module#259]
### 0. Before Your ASK

1. Try to find an answer by reading a [FAQ](https://github.com/chobits/ngx_http_proxy_connect_module/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aquestion).

### Ⅰ. Issue Description
error in nginx Make process

### Ⅱ. Describe what happened
try nginx 1.21.0 and 1.24.0
cd nginx file
'configure' -- ok
'make': some errors happens
example:  
src/event/ngx_event_openssl.c: In function ‘ngx_ssl_load_certificate_key’:
src/event/ngx_event_openssl.c:729:9: error: ‘ENGINE_by_id’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  729 |         engine = ENGINE_by_id((char *) p);
      |         ^~~~~~
In file included from src/event/ngx_event_openssl.h:22,
                 from src/core/ngx_core.h:84,
                 from src/event/ngx_event_openssl.c:9:
/usr/include/openssl/engine.h:336:31: note: declared here
  336 | OSSL_DEPRECATEDIN_3_0 ENGINE *ENGINE_by_id(const char *id);
      |                               ^~~~~~~~~~~~
...
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:888: objs/src/event/ngx_event_openssl.o] Error 1
make[1]: Leaving directory '/home/ec2-user/nginx-1.21.0'
make: *** [Makefile:10: build] Error 2

### Ⅲ. Describe what you expected to happen
how to solve this problem

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.  wget https://github.com/chobits/ngx_http_proxy_connect_module/archive/refs/heads/master.tar.gz
2. sudo wget http://nginx.org/download/nginx-1.21.0.tar.gz
3. tar
4. cd nginx
5. ./configure --user=www --group=www --prefix=/usr/local/nginx --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-threads --add-module=/home/ec2-user/ngx_http_proxy_connect_module-master
6. make

### Ⅴ. Anything else we need to know?

1. If applicable, add nginx  [debug log](http://nginx.org/en/docs/debugging_log.html).
2.
3.

### Ⅵ. Environment:

1. Tengine/Nginx/OpenResty version (use `sbin/nginx -v`):
2. Which [patch](https://github.com/chobits/ngx_http_proxy_connect_module#select-patch) do you use?

**Comment by bangzhuX** [comment]
and i do the patch and make again, stiil have the problem

**Comment by chobits** [comment]
hi

Two problem I found here:

1. It seemed that you didnt patch nginx source with proper patch provied by proxy_connect module. see here for how to patch & build this module: https://github.com/chobits/ngx_http_proxy_connect_module#install

2. The conpilation error seems a SSL compilation error, you can disable this module to check whether it still exists.

---

BTW, new triggered testing for 1.24.0 has passed, you can check it here: https://github.com/chobits/ngx_http_proxy_connect_module/actions/runs/4686133835/jobs/8303899129?pr=260

**Comment by bangzhuX** [comment]
Thanks, I'll check it out.

Xiaochen Wang ***@***.***> 于2023年4月13日周四 14:27写道：
