### ISSUE TITLE
debian repository

### ISSUE THREAD

**Issue by JohnRDOrazio** [chobits/ngx_http_proxy_connect_module#271]
## Why you need it?
This is more of a commodity: seeing that Ondrej Sury has some great debian repos with updated `nginx`, it would be very useful to have a debian repo with an updated `nginx` that is built with this module.

## How it could be?
Similar to Ondrej Sury's debian repo ( https://github.com/oerdnj/deb.sury.org ) - `ppa:ondrej/nginx`, there could be a debian repo with a ready built `nginx` that includes this module.

## Other related information
I opened a [ticket](https://github.com/oerdnj/deb.sury.org/issues/1955) on Ondrej Sury's github repo requesting a similar build, but if it's too much for Ondrej to handle, perhaps there could be a collaboration that would make it easier to implement?

**Comment by chobits** [comment]
I hope others can help with the Debian package. 🙏I don't want to spend too much time on packaging systems. 

However, I can assist in tracking down building or testing issues by opening an issue. Just let me know if you need help. 

Also, keep in mind that this module cannot be provided as a dynamic nginx library for installation into a standard nginx core package (for example “dep: [nginx-core](https://packages.debian.org/bullseye/nginx-core)"）, as it requires patching the nginx core.

**Comment by chobits** [comment]
mark it as stale
