### ISSUE TITLE
ssh its work?

### ISSUE THREAD

**Issue by anonv2ray** [chobits/ngx_http_proxy_connect_module#272]
am stuck on how to install also I want to know if this proxy can use to restrict/bypass the firewall, and connect to ssh

**Comment by chobits** [comment]
> am stuck on how to install

The [doc](https://github.com/chobits/ngx_http_proxy_connect_module#install) pretty clearly states how to build. If you're unable or don't know how to compile it yourself, then this is not the tool for you. However, if you have any specific compilation issues, please state them directly.

> also I want to know if this proxy can use to restrict/bypass the firewall, and connect to ssh

I'm not sure how to answer your question. The description is too broad.

* `firewall` :  unable to answer
* `connect to ssh` :  The CONNECT tunnel protocol does not care about the type of data that is being passed over it. The client is responsible for determining which protocol to use. Ensure that you understand how the CONNECT tunnel works before using it.
