### ISSUE TITLE
502 error  (111:Unknown error)

### ISSUE THREAD

**Issue by aAAa423** [chobits/ngx_http_proxy_connect_module#279]
Occasionally, this error message may appear,Checking the debug log and discovering that the IP address of the other party has been obtained.What is the general reason for this
proxy_connect: upstream connect time failed (111: Unknown error ) while connecting to upstream

**Comment by chobits** [comment]
The proxy wanna to connect upstream peer, but it failed, with which there is some errors occuring during the TCP
 3-way handshake, for example the peer send RST for your first SYN. It may be the firewall or local network problem.

If you find "timed out" string in error.log, it means that the proxy tries to connect upstream peer, but it timed out.

**Comment by aAAa423** [comment]
> The proxy wanna to connect upstream peer, but it failed, with which there is some errors occuring during the TCP 3-way handshake, for example the peer send RST for your first SYN. It may be the firewall or local network problem.
> 
> If you find "timed out" string in error.log, it means that the proxy tries to connect upstream peer, but it timed out. A possible case is that the proxy send SYN to upstream peer, but it cannot receive 2nd SYN+ACK from the peer.
> 
> If your proxy server is in mainland CN and the website you're trying to access is outside of CN, you may experience connection issues accessing it usually.

我是从内地访问腾讯的域名，应该不存在墙或者其他问题，偶尔会出现这个去不情况，导致系统异常，所以想请教下网友们怎么解决

**Comment by aAAa423** [comment]
> The proxy wanna to connect upstream peer, but it failed, with which there is some errors occuring during the TCP 3-way handshake, for example the peer send RST for your first SYN. It may be the firewall or local network problem.
> 
> If you find "timed out" string in error.log, it means that the proxy tries to connect upstream peer, but it timed out. A possible case is that the proxy send SYN to upstream peer, but it cannot receive 2nd SYN+ACK from the peer.
> 
> If your proxy server is in mainland CN and the website you're trying to access is outside of CN, you may experience connection issues accessing it usually.

我是从内地访问腾讯的域名，应该不存在墙或者其他网络上的问题，偶尔会出现这个去不情况，导致系统异常，所以想请教下网友们怎么解决

**Comment by chobits** [comment]
> > The proxy wanna to connect upstream peer, but it failed, with which there is some errors occuring during the TCP 3-way handshake, for example the peer send RST for your first SYN. It may be the firewall or local network problem.
> > If you find "timed out" string in error.log, it means that the proxy tries to connect upstream peer, but it timed out. A possible case is that the proxy send SYN to upstream peer, but it cannot receive 2nd SYN+ACK from the peer.
> > If your proxy server is in mainland CN and the website you're trying to access is outside of CN, you may experience connection issues accessing it usually.
> 
> 我是从内地访问腾讯的域名，应该不存在墙或者其他网络上的问题，偶尔会出现这个情况，导致系统异常，所以想请教下网友们有什么办法解决

It appears that we could add reconnect logic to this module, as it currently lacks any retry mechanisms for connection failures. But I do not have any availabe time to implement this feature at the moment.
