### ISSUE TITLE
Compilation failed on ubuntu22.04

### ISSUE THREAD

**Issue by ZxyNull0** [chobits/ngx_http_proxy_connect_module#290]
I used the following script to install openresty and add this module, but when executing the make command, an error occurred.
```
#!/bin/bash
cd /usr/local/src

wget https://openresty.org/download/openresty-1.21.4.2.tar.gz
wget https://github.com/chobits/ngx_http_proxy_connect_module/archive/refs/tags/v0.0.5.tar.gz


tar -xvzf openresty-1.21.4.2.tar.gz
tar -xvzf v0.0.5.tar.gz

apt-get update
apt-get install -y libpcre3 libpcre3-dev
apt-get install -y openssl libssl-dev
apt-get install -y zlib1g zlib1g-dev
apt-get install -y build-essential

cd openresty-1.21.4.2
./configure --prefix=/usr/local/openresty --with-http_ssl_module --with-stream_ssl_module --add-module=/usr/local/src/ngx_http_proxy_connect_module-0.0.5
patch -d build/nginx-1.21.4/ -p 1 < /usr/local/src/ngx_http_proxy_connect_module-0.0.5/patch/proxy_connect_rewrite_102101.patch
make && make install

```
![](https://secure2.wostatic.cn/static/ur2ondfqL5rPaFBBbJ7AE1/aeb55f35f21795fc082a40f768a332d.png?auth_key=1700811300-sMVmT74VYF7dervLGmaq9y-0-fce25e6662d0957e4463e726a75b8700)
But it can be successfully installed on ubuntu20.04, and the versions of openssl are all 1.1.1

**Comment by chobits** [comment]
> but when executing the make command, an error occurred.
What error message do you get, you can post it here.

**Comment by chen-chao** [comment]
@ZxyNull0  Perhaps you can try the script provided by `[docker-nginx](https://github.com/nginxinc/docker-nginx)`. I successfully built the `lua-module` with `ngx_http_proxy_connect_module` into a alpine docker based on it: [docker-ngx_http_proxy_connect](https://github.com/chen-chao/docker-ngx_http_proxy_connect).

**Comment by chobits** [comment]
stale, I think we. could close this one now. THanks for your reply @chen-chao
