### ISSUE TITLE
quic protocol

### ISSUE THREAD

**Issue by Ryenum** [chobits/ngx_http_proxy_connect_module#292]
I have a problem, I have a server that supports the quic protocol, but I still use the http2 protocol when I use it as a forward proxy to access other websites that support http3. Why?

**Comment by chobits** [comment]
Currently it does not supported h2/h3(quic) protocol.

H2 support is under development https://github.com/chobits/ngx_http_proxy_connect_module/pull/278.
H3 support, we do not have a plan now.
