### ISSUE TITLE
Compilation failed ngx_http_proxy_connect_module-0.0.5 @ nginx-1.24.0 @ ubuntu22.04 

### ISSUE THREAD

**Issue by herofqy** [chobits/ngx_http_proxy_connect_module#295]
## cmd :
```sh
./configure --prefix=/home/fqy/nginx_forward_proxy --with-stream --with-stream_ssl_preread_module --with-stream_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_auth_request_module --with-http_addition_module --with-http_realip_module  --with-http_ssl_module --add-module=/home/fqy/nginx-1.24.0/ngx_http_proxy_connect_module-0.0.5

make
```
## err log :

......(orher log)
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/stream \
        -o objs/addon/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.o \
        /home/fqy/nginx-1.24.0/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.c
/home/fqy/nginx-1.24.0/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.c: In function ‘ngx_http_proxy_connect_handler’:
/home/fqy/nginx-1.24.0/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.c:1498:30: error: ‘ngx_http_request_t’ {aka ‘struct ngx_http_request_s’} has no member named ‘connect_host’; did you mean ‘connection’?
 1498 |             url.url.len = r->connect_host.len;
      |                              ^~~~~~~~~~~~
      |                              connection
/home/fqy/nginx-1.24.0/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.c:1499:31: error: ‘ngx_http_request_t’ {aka ‘struct ngx_http_request_s’} has no member named ‘connect_host’; did you mean ‘connection’?
 1499 |             url.url.data = r->connect_host.data;
      |                               ^~~~~~~~~~~~
      |                               connection
/home/fqy/nginx-1.24.0/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.c:1503:26: error: ‘ngx_http_request_t’ {aka ‘struct ngx_http_request_s’} has no member named ‘connect_host’; did you mean ‘connection’?
 1503 |         url.url.len = r->connect_host.len;
      |                          ^~~~~~~~~~~~
      |                          connection
/home/fqy/nginx-1.24.0/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.c:1504:27: error: ‘ngx_http_request_t’ {aka ‘struct ngx_http_request_s’} has no member named ‘connect_host’; did you mean ‘connection’?
 1504 |         url.url.data = r->connect_host.data;
      |                           ^~~~~~~~~~~~
      |                           connection
/home/fqy/nginx-1.24.0/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.c:1507:27: error: ‘ngx_http_request_t’ {aka ‘struct ngx_http_request_s’} has no member named ‘connect_port_n’; did you mean ‘connection’?
 1507 |     url.default_port = r->connect_port_n;
      |                           ^~~~~~~~~~~~~~
      |                           connection
/home/fqy/nginx-1.24.0/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.c:1552:55: error: ‘ngx_http_request_t’ {aka ‘struct ngx_http_request_s’} has no member named ‘connect_port_n’; did you mean ‘connection’?
 1552 |     u->resolved->port = (in_port_t) (url.no_port ? r->connect_port_n : url.port);
      |                                                       ^~~~~~~~~~~~~~
      |                                                       connection
In file included from src/core/ngx_core.h:60,
                 from /home/fqy/nginx-1.24.0/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.c:7:
/home/fqy/nginx-1.24.0/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.c:1588:27: error: ‘ngx_http_request_t’ {aka ‘struct ngx_http_request_s’} has no member named ‘connect_host’; did you mean ‘connection’?
 1588 |                       &r->connect_host);
      |                           ^~~~~~~~~~~~
src/core/ngx_log.h:86:67: note: in definition of macro ‘ngx_log_error’
   86 |     if ((log)->log_level >= level) ngx_log_error_core(level, log, __VA_ARGS__)
      |                                                                   ^~~~~~~~~~~
/home/fqy/nginx-1.24.0/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.c: In function ‘ngx_http_proxy_connect_allow_handler’:
/home/fqy/nginx-1.24.0/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.c:1664:41: error: ‘ngx_http_request_t’ {aka ‘struct ngx_http_request_s’} has no member named ‘connect_port_n’; did you mean ‘connection’?
 1664 |             if ((ports[i][1] == 0 && r->connect_port_n == ports[i][0])
      |                                         ^~~~~~~~~~~~~~
      |                                         connection
/home/fqy/nginx-1.24.0/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.c:1665:39: error: ‘ngx_http_request_t’ {aka ‘struct ngx_http_request_s’} has no member named ‘connect_port_n’; did you mean ‘connection’?
 1665 |                 || (ports[i][0] <= r->connect_port_n && r->connect_port_n <= ports[i][1]))
      |                                       ^~~~~~~~~~~~~~
      |                                       connection
/home/fqy/nginx-1.24.0/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.c:1665:60: error: ‘ngx_http_request_t’ {aka ‘struct ngx_http_request_s’} has no member named ‘connect_port_n’; did you mean ‘connection’?
 1665 |                 || (ports[i][0] <= r->connect_port_n && r->connect_port_n <= ports[i][1]))
      |                                                            ^~~~~~~~~~~~~~
      |                                                            connection
/home/fqy/nginx-1.24.0/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.c:1673:16: error: ‘ngx_http_request_t’ {aka ‘struct ngx_http_request_s’} has no member named ‘connect_port_n’; did you mean ‘connection’?
 1673 |         if (r->connect_port_n == 443 || r->connect_port_n == 563) {
      |                ^~~~~~~~~~~~~~
      |                connection
/home/fqy/nginx-1.24.0/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.c:1673:44: error: ‘ngx_http_request_t’ {aka ‘struct ngx_http_request_s’} has no member named ‘connect_port_n’; did you mean ‘connection’?
 1673 |         if (r->connect_port_n == 443 || r->connect_port_n == 563) {
      |                                            ^~~~~~~~~~~~~~
      |                                            connection
make[1]: *** [objs/Makefile:1497：objs/addon/ngx_http_proxy_connect_module-0.0.5/ngx_http_proxy_connect_module.o] .....(other log)

**Comment by yoloz** [comment]
debian12, nginx:1.27.1, module:0.0.7, appear this error

**Comment by yoloz** [comment]
> debian12, nginx:1.27.1, module:0.0.7, appear this error

execute `patch -p1 < ../ngx_http_proxy_connect_module-0.0.7/patch/proxy_connect_rewrite_102101.patch` will solve this problem

download readme patch link output:`patch: **** Only garbage was found in the patch input.`,maybe this file not right, use source code path
