### ISSUE TITLE
Does the module support tor proxy ?

### ISSUE THREAD

**Issue by TheShadowMax** [chobits/ngx_http_proxy_connect_module#298]
Good afternoon, I am trying to organize proxying by means of this module.

torrc

```
DataDirectory /var/lib/tor/proxy
HTTPTunnelPort 7272
RunAsDaemon 1
```

and config for nginx

```
server {
    listen 80;
    server_name localhost;

    proxy_connect;

    location / {
        proxy_set_header Host "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.onion";
        proxy_pass http://127.0.0.1:7272;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

But unfortunately nothing happens.
and I still get the error that my host does not support http connect from tor. and proxying does not happen.

which way is up?
and whether this scheme is possible with this module.

**Comment by chobits** [comment]
> and I still get the error that my host does not support http connect from tor. and proxying does not happen.
whats error message of your client report? You could [use `curl` command to test its connectivity ](https://github.com/chobits/ngx_http_proxy_connect_module?tab=readme-ov-file#example-for-curl).

**Comment by chobits** [comment]
mark as stale, if you still have issue, feel free to reopen it.
