### ISSUE TITLE
Automatically generating the destination server certificate?

### ISSUE THREAD

**Issue by xlxxxxxxxl** [chobits/ngx_http_proxy_connect_module#303]
When using nginx as a forward proxy, this module supports importing the root certificate and automatically generating the destination server certificate?
 if not, please tell me clues that may be useful, preferably a module like this
thank you！

**Comment by chobits** [comment]
This module could not do this, its only used as pure HTTP tunnel proxy, just proxying the raw data in the HTTP tunnel.

**Comment by chobits** [comment]
I'm closing this for now. Feel free to reopen or create a new one if you have any further issues.
