### ISSUE TITLE
proxy_disable_redirections

### ISSUE THREAD

**Issue by ben74** [chobits/ngx_http_proxy_connect_module#304]
## Why you need it?
In order to allow people to export data to their external webservice but not allowing any redirections so they can't probe my inner architecture ( their call replies are logged within my app )

## How it could be?
proxy_disable_redirections yes

**Comment by chobits** [comment]
I don't fully understand this requirement .

Could you give me some example and your use case?

**Comment by chobits** [comment]
stale so I'm closing , feel free to reopen it if you still have this requirement and pls provide more details
