### ISSUE TITLE
Is there a function that can combine this module with OpenResty to implement the approximate functionality of Burp?

### ISSUE THREAD

**Issue by Paper-Dragon** [chobits/ngx_http_proxy_connect_module#306]
- Install a certificate into the operating system. Decrypt traffic from forward proxies
- Use lua to modify the contents of the body, and then proxy_pass to an address

Does anyone know how to do it?

**Comment by chobits** [comment]
> Use lua to modify the contents of the body, and then proxy_pass to an address

This goes against the module's design philosophy. This module is intended to be a traffic proxy, not to unpack and manipulate traffic.

So i guess if you wanna meet this, you need to rewrite the CONNECT tunnel proxy and modify logic in pure lua within stream module. This module is only design to proxy.
