### ISSUE TITLE
is there support for nginx 1.26?

### ISSUE THREAD

**Issue by CrashLaker** [chobits/ngx_http_proxy_connect_module#307]

**Comment by FrostKiwi** [comment]
Wondering the same here.

Specifically as a NixOS user:

NixOS defines this repo as a module here: https://github.com/NixOS/nixpkgs/blob/619d94523e65b1f04c5c54b7840f9604367fd3a1/pkgs/servers/http/nginx/modules.nix#L309
With the release of NixOS 24.05 NGINX 1.26 became the standard version and this module has thus lost support on NixOS in the latest version.

**Comment by chobits** [comment]
Try to test 1.26.1, let's wait the CI/CD results in this PR.

**Comment by chobits** [comment]
See the result https://github.com/chobits/ngx_http_proxy_connect_module/actions/runs/10017879283/job/27692592450?pr=315, it worked for nginx-1.26.1 and 1.27.0. I'll complete the whole progress later.

**Comment by FrostKiwi** [comment]
> See the result https://github.com/chobits/ngx_http_proxy_connect_module/actions/runs/10017879283/job/27692592450?pr=315, it worked for nginx-1.26.1 and 1.27.0. I'll complete the whole progress later.

Looking forward to a new release. 👍

**Comment by chobits** [comment]
resolved, see the latest release for this support: https://github.com/chobits/ngx_http_proxy_connect_module/releases/tag/v0.0.7
