### ISSUE TITLE
"config" file has a problem

### ISSUE THREAD

**Issue by biienu** [chobits/ngx_http_proxy_connect_module#314]
## Problems encountered when configuring nginx
```shell
configuring additional modules
adding module in /opt/nginx_proxy/ngx_http_proxy_connect_module/
/opt/nginx_proxy/ngx_http_proxy_connect_module//config: line 2: $'\r': command not found
/opt/nginx_proxy/ngx_http_proxy_connect_module//config: line 15: syntax error: unexpected end of file
```
![image](https://github.com/user-attachments/assets/1c498809-45fd-4b53-8813-73c49f5f6203)

**Comment by chobits** [comment]
Could you give more details. with your info, we could not help pinpoint the issue. 

But I guess  you edited the config file and saveded it, then your editor may append some special chars.

**Comment by biienu** [comment]
> Could you give more details. with your info, we could not help pinpoint the issue.
> 
> But I guess you edited the config file and saveded it, then your editor may append some special chars.

Yes, The config file was changed by me. Now it normally works when recovering the file.
Thanks your repley!

**Comment by chobits** [comment]
> > Could you give more details. with your info, we could not help pinpoint the issue.
> > But I guess you edited the config file and saveded it, then your editor may append some special chars.
> 
> Yes, The config file was changed by me. Now it normally works when recovering the file. Thank you for your reply!

COol. think it as resolved!
