### ISSUE TITLE
I also have the same problem.

### ISSUE THREAD

**Issue by ghost** [chobits/ngx_http_proxy_connect_module#316]
> I have the same problem
> 
> > # 无法启用 ssl
> > ....
> > ## 问题
> > 当我**关闭**ssl 时（配置文件第一行删除ssl参数）代理工作正常 当我**启用**ssl时（如上配置）出现以上的测试问题
> > 我看您这边配置成功了，是可以支持 客户端 -> `HTTPS` -> 代理服务 -> `HTTP/HTTPS` -> 目标服务器 , 但是我不知道问题出在哪里，能否给出一些意见。谢谢
> 
> I have the same problem too. "client sent plain HTTP request to HTTPS port while reading client request headers,"

hi, your configuration is right, but ur constructed curl command is not right, see my latest documentation here: https://github.com/chobits/ngx_http_proxy_connect_module#example-for-curl-connect-request-in-https

![image](https://user-images.githubusercontent.com/623062/223040621-4136f155-56b9-4130-bd3a-0dac145fef85.png)

```
$ curl https://nginx.org/ -sv -o/dev/null -x https://<your-nginx-ip>:<your-nginx-port> --proxy-insecure
```

_Originally posted by @chobits in https://github.com/chobits/ngx_http_proxy_connect_module/issues/22#issuecomment-1455553322_
            

>

**Comment by biienu** [comment]
# **Bellow is my nginx`config,**
![image](https://github.com/user-attachments/assets/c77413c4-68fb-45c3-be4f-81c50bfef15d)

## and I let 'biienu.crt' file work as a trusted certificate in "/etc/pki/ca-trust/source/anchors" directory.
When I was testing, I encountered the following problem:
![image](https://github.com/user-attachments/assets/8cc15051-cede-473f-9196-f4c7aac9892d)

![image](https://github.com/user-attachments/assets/f5d93caa-bb0f-4cf4-b152-7bce479003a4)


# can you help me to solve it?

**Comment by chobits** [comment]
Curl error reports showed that it has no `--proxy-insecure` command. I think you should try to resolve it from this point, which is beyond me

**Comment by biienu** [comment]
I encountered the following problem when useing the '-k' parameter instead of the '--proxy-insecure' parameter. **so what is the reason for this?**

![image](https://github.com/user-attachments/assets/60abf775-b965-4e11-ba29-d5f1e40aee94)

**Comment by biienu** [comment]
> Curl error reports showed that it has no `--proxy-insecure` command. I think you should try to resolve it from this point, which is beyond me

**Comment by biienu** [comment]
> I encountered the following problem when useing the '-k' parameter instead of the '--proxy-insecure' parameter. **so what is the reason for this?**
> 
> ![image](https://private-user-images.githubusercontent.com/99333121/350765939-60abf775-b965-4e11-ba29-d5f1e40aee94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NjMzNTMsIm5iZiI6MTcyMTU2MzA1MywicGF0aCI6Ii85OTMzMzEyMS8zNTA3NjU5MzktNjBhYmY3NzUtYjk2NS00ZTExLWJhMjktZDVmMWU0MGFlZTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDExNTczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNWZhOGU3ZjVjZWEwZjMwZjA1ZWQ5NDVhZmZlYjBkNmM0MTBjYmY5ZDMyYmY2ZmM2MTUwNGFmZGQwYzExZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w4ZErcv4NHwlOoPCD5y0i9SoaNemM5F5icT2tbItcqc)

@chobits

**Comment by chobits** [comment]
the user has closed its account, we may not contact him again
