### ISSUE TITLE
rate limiting requests

### ISSUE THREAD

**Issue by dl-senecaso** [chobits/ngx_http_proxy_connect_module#319]
is it possible to use the rate limiting functionality of nginx with this module?

Using the following config, I am able to successfully rate limit `http` requests, but anything connecting to `https` appears to be unlimited.  So it would seem that the `CONNECT` requests are not limited at all.  Is there a way to achieve this?  My suspicion is that this is expected, but I would like to confirm before I have to try to find another solution.

```
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    limit_req_zone $host zone=images:10m rate=1r/m;

    server {
        listen 8080;

        resolver 1.1.1.1 ipv6=off;

        # forward proxy for CONNECT requests
        proxy_connect;
        proxy_connect_allow            443;
        proxy_connect_connect_timeout  10s;
        proxy_connect_data_timeout     10s;

        location / {
            limit_req zone=images;

            proxy_pass http://$host;
            proxy_set_header Host $host;
        }
    }
}
```

**Comment by chobits** [comment]
The requests (like the SSL requests) proxied by proxy_connect under the CONNECT tunnel could not be limited by rate_limiting module. Because the proxy_connect module could not know how many requests are proxied in the tunnel, it will not and could not parse the proxied data flow.

But you can limit the connection establish rate of CONNECT tunnel using limit_conn module.
