### ISSUE TITLE
use this module could not pull docker image// 基于此模块部署nginx正向代理拉取docker镜像报错

### ISSUE THREAD

**Issue by opser-gavin** [chobits/ngx_http_proxy_connect_module#321]
如题，nginx编译添加这个模块，然后certbot配置HTTPS代理，通过此代理可以访问google/youtube/xvideos.....等，
但配置docker拉取镜像会报错，请教下怎么解决
# docker  pull nginx
Using default tag: latest
Error response from daemon: Head "https://registry-1.docker.io/v2/library/nginx/manifests/latest": Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fnginx%3Apull&service=registry.docker.io": Bad Gateway

**Comment by chobits** [comment]
Pls provide more details, with your description, we cannot understand what happens, especially minimal step to reproduce.

And you could use tcpdump tool to check if the proxied stream failed when connecting or the real data flow has been proxied to destination.
