### ISSUE TITLE
'Connection timed out' errors

### ISSUE THREAD

**Issue by concreted** [chobits/ngx_http_proxy_connect_module#35]
I've configured proxy_connect with this forward proxy configuration https://gist.github.com/concreted/769bdc0a451d82f020523dfeca5829dc and it is proxying traffic as expected. I configured Chrome to use the proxy server with this config. However I see many instances of this error in the Nginx `error.log`:

```
2018/02/05 22:18:57 [error] 10#0: *55 upstream timed out (110: Connection timed out) while connecting to upstream(proxy_connect), client: 192.168.99.1, server: , request: "CONNECT i.imgur.com:443 HTTP/1.1", host: "i.imgur.com:443"
```

In `access.log`, there is a corresponding CONNECT request attempt to the host, in this case `i.imgur.com`:
```
192.168.99.1 - - [05/Feb/2018:22:24:32 +0000] "CONNECT i.imgur.com:443 HTTP/1.1" 000 1477 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) electron-quick-start/1.0.0 Chrome/58.0.3029.110 Electron/1.7.11 Safari/537.36"
```

What could be causing this error, and could it cause problems later? It seems like the CONNECT calls are always timing out, but the proxy is still returning the correct results to Chrome, and Chrome doesn't show any network errors.

**Comment by chobits** [comment]
hi @concreted 

```
2018/02/05 22:18:57 [error] 10#0: *55 upstream timed out (110: Connection timed out) while connecting to upstream(proxy_connect), client: 192.168.99.1, server: , request: "CONNECT i.imgur.com:443 HTTP/1.1", host: "i.imgur.com:443"
```

This means proxy_connect module tried to read data from upstream( '127.0.0.1:443' server from ur configure) , but upstream server did not return any data more than 10s.

>  It seems like the CONNECT calls are always timing out, but the proxy is still returning the correct results to Chrome, and Chrome doesn't show any network errors.

Yeah, I think that it is not a problem, chrome (client) / real backend server would keepalive an idle connection alive, but proxy_connect module's configure ` proxy_connect_read_timeout     10s;` would break this keepalive connection if there is no data readed from upstream for >10s.

If you configures `proxy_connect_{read/write}_timeout` directive with high number, `Connection timed out` errors will occur rarely, and it can offer little performance gains.

**Comment by concreted** [comment]
I see, that makes sense. Thanks for the explanation!
