### ISSUE TITLE
Forward incoming https based only on domain name

### ISSUE THREAD

**Issue by octgsoftware** [chobits/ngx_http_proxy_connect_module#43]
Can this module be used to forward requests coming from the internet?  If so can  you point me to an example of this setup.  I do not care about caching or routing traffic coming out of my vms.

My setup is one vm running nginx with a public IP and multiple others running various combinations or web servers on other vms on internal IPs.

The the vms that need https are already handling their own https with letsencrypt or paid certs because they all had public IPs before.  I only want the the vm running nginx to forward the traffic based on the domain name to the proper vm.  I do not want to intercept the traffic and break the encryption. This is working for http, but it seems nginx cannot forward the https the way I want.

Is this module the right tool to use?  I am most familiar with nginx which is why I am hesitant to use Squid, Apache Traffic Server, or similar.

**Comment by octgsoftware** [comment]
Thank you for the reply. I read the digital ocean link.  This is not exactly what I am trying to do, but was the alternative I was considering.

For this to work I will need to remove https handling on my guests and let this be take care of on the vm running nginx which is only intended to route the traffic to the appropriate vm based on domain name.

I wanted each guest to handle their own https and only have nginx or something else route the traffic to the guest that should get the traffic.

Example:
vm-nginx runs on a public IP and is only intended to route traffic to other vms.

vm-www.domain-http.com receives traffic for http://www.domain-http.com.  This works if www.domain-http.com points to the public IP of vm-nginx.

vm-www.domain-needs-https.com handles its own https.  This works if vm-www.domain-needs-https.com has its own public IP, but I do not have enough public IP for all the vms.

Is no way to make this work without letting vm-nginx handle the https for vm-www.domain-needs-https.com?

**Comment by chobits** [comment]
hi @octgsoftware 

This module(ngx_http_proxy_connect_module) cannot work for your task.

@Gondost 's [comment](https://github.com/chobits/ngx_http_proxy_connect_module/issues/43#issuecomment-389581016) gave the right way, which uses ngx_stream_ssl_preread_module to preread SNI name and map SNI name to right backend address.

**Comment by chobits** [comment]
think it resolved, feel free to reopen if you have problem still
