### ISSUE TITLE
请问windows下面的nginx如何打补丁

### ISSUE THREAD

**Issue by carterzk** [chobits/ngx_http_proxy_connect_module#44]
我这里需要做一个多端口多路由的正向代理，打算用nginx来操作；环境为windows；发现windows下面nginx无法正向代理https，但是没找到windows下面d的nginx如何使用这个patch文件的方法。请问windows下面如何对nginx打patch

**Comment by carterzk** [comment]
明白了。重新在windows下面编译前打patch。。

**Comment by OldBoyFromFDU** [comment]
> 明白了。重新在windows下面编译前打patch。。

Emmm,怎么在windows下面进行patch包升级呢~我也需要对Nginx进行这个patch的升级。
