### ISSUE TITLE
multi-proxy // How to use two cascaded nginx servers to proxy traffic?

### ISSUE THREAD

**Issue by cuiyanwei** [chobits/ngx_http_proxy_connect_module#49]
多级代理怎么用 ？比如 二级  二台 nginx  第一台nginx 仅做一个转发 由第一台nginx 转发到第二台nginx 通过第二台nginx 连接外网 

---
EN: 
How to use two cascaded nginx servers to proxy traffic?
The first nginx proxies client's traffic to the second.
And the second nginx proxies traffic to the internet.

**Comment by chobits** [comment]
```
client -> nginx-1 -> nginx-2
```

* nginx-1开启 tcp代理功能，把原始数据包转给nginx-2
 * 可以使用tcp proxy做tcp代理: https://github.com/yaoweibin/nginx_tcp_proxy_module
 * 也可以stream proxy做tcp代理：http://nginx.org/en/docs/stream/ngx_stream_proxy_module.html
* nginx-2开启proxy_connect（本模块）做CONNECT tunnel并代理到访问外网

**Comment by cuiyanwei** [comment]
Thanks for reply

**Comment by chobits** [comment]
think it resolved, closing it. Reopen if you have other question.
