### ISSUE TITLE
[TODO] Support nginx 1.15.x

### ISSUE THREAD

**Issue by railjty** [chobits/ngx_http_proxy_connect_module#55]
The patch can't apply to nginx 1.15.1 now, so I can't use the module. May you add the support for nginz 1.15.1?

**Comment by chobits** [comment]
Yes, I'm working on this problem. It may be finished due to the end of July.

**Comment by lcl1995225** [comment]
thanks.I need to use it in nginx 1.15 ,too.

**Comment by chobits** [comment]
hi @genevera 

Thanks for your report. I'll test it soon:)

**Comment by chobits** [comment]
These commits of nginx makes proxy_connect*.patch failed:

```
commit f11a9cbdd0f5806131e4308d2ce98a2a97ca4007
Author: Ruslan Ermilov <ru@nginx.com>
Date:   Thu Jun 7 20:01:41 2018 +0300

    Added r->schema.

    For HTTP/1, it keeps scheme from the absolute form of URI.
    For HTTP/2, the :scheme request pseudo-header field value.

diff --git a/src/http/ngx_http_request.c b/src/http/ngx_http_request.c
index 210994b6..0432c91b 100644
--- a/src/http/ngx_http_request.c
+++ b/src/http/ngx_http_request.c
@@ -987,6 +987,11 @@ ngx_http_process_request_line(ngx_event_t *rev)
                 return;
             }

+            if (r->schema_end) {
+                r->schema.len = r->schema_end - r->schema_start;
+                r->schema.data = r->schema_start;
+            }
+
             if (r->host_end) {

                 host.len = r->host_end - r->host_start;

commit 70b6e7a299e6488c2f59f1768c600921bd08a2d7
Author: Ruslan Ermilov <ru@nginx.com>
Date:   Thu Jun 7 19:53:43 2018 +0300

    Removed extraneous check while processing request line.

diff --git a/src/http/ngx_http_request.c b/src/http/ngx_http_request.c
index 47c62d9f..210994b6 100644
--- a/src/http/ngx_http_request.c
+++ b/src/http/ngx_http_request.c
@@ -987,7 +987,7 @@ ngx_http_process_request_line(ngx_event_t *rev)
                 return;
             }

-            if (r->host_start && r->host_end) {
+            if (r->host_end) {

                 host.len = r->host_end - r->host_start;
                 host.data = r->host_start;
```

**Comment by chobits** [comment]
First trying to simplify patch: https://github.com/chobits/ngx_http_proxy_connect_module/pull/59.
Will make it work for nginx-1.15.x in next pr soon.

**Comment by chobits** [comment]
Hi all,

This module has supported nginx-1.15.x (current mainline version nginx-1.15.1~nginx.1.15.2). You can check lastest master branch.

For the detail of development, see https://github.com/chobits/ngx_http_proxy_connect_module/pull/60.

**Comment by wxy8435** [comment]
@chobits Hi,I have test on my own machines ,but it does not work . using the  nginx-1.15.2.tar.gz and your proxy_connect_rewrite_1015.patch and got no errors when i  recomplied the source code  .

nginx version: nginx/1.15.2
built by clang 9.0.0 (clang-900.0.37)
built with OpenSSL 1.0.2o  27 Mar 2018
TLS SNI support enabled
configure arguments: --prefix=/usr/local/Cellar/nginx/nginx-1.15.2 --sbin-path=/usr/local/Cellar/nginx/nginx-1.15.2/bin/nginx --with-cc-opt='-I/usr/local/opt/pcre/include -I/usr/local/opt/openssl/include' --with-ld-opt='-L/usr/local/opt/pcre/lib -L/usr/local/opt/openssl/lib' --conf-path=/usr/local/etc/nginx/nginx.conf --pid-path=/usr/local/var/run/nginx.pid --lock-path=/usr/local/var/run/nginx.lock --http-client-body-temp-path=/usr/local/var/run/nginx/client_body_temp --http-proxy-temp-path=/usr/local/var/run/nginx/proxy_temp --http-fastcgi-temp-path=/usr/local/var/run/nginx/fastcgi_temp --http-uwsgi-temp-path=/usr/local/var/run/nginx/uwsgi_temp --http-scgi-temp-path=/usr/local/var/run/nginx/scgi_temp --http-log-path=/usr/local/var/log/nginx/access.log --error-log-path=/usr/local/var/log/nginx/error.log --with-debug --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-ipv6 --with-mail --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --_add-module=/usr/local/Cellar/nginx/ngx_http_proxy_connect_module-master_

and when i test 
userdeMacBook-Air:nginx user$ curl  -v -x 10.251.199.17:3128 https://www.baidu.com
* Rebuilt URL to: https://www.baidu.com/
*   Trying 10.251.199.17...
* TCP_NODELAY set
* Connected to 10.251.199.17 (127.0.0.1) port 3128 (#0)
* Establish HTTP proxy tunnel to www.baidu.com:443
> CONNECT www.baidu.com:443 HTTP/1.1
> Host: www.baidu.com:443
> User-Agent: curl/7.54.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 502 Bad Gateway
< Server: nginx/1.15.2
< Date: Mon, 06 Aug 2018 04:27:07 GMT
< Content-Type: text/html
< Content-Length: 173
< Connection: close
<
* Received HTTP code 502 from proxy after CONNECT
* Closing connection 0
curl: (56) Received HTTP code 502 from proxy after CONNECT"

the local nginx logs display :
2018/08/06 12:27:07 [error] 96389#0: *34 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 10.251.199.17, server: localhost, request: "CONNECT www.baidu.com:443 HTTP/1.1", host: "www.baidu.com:443"

so how can i test my recomplied nginx is correct support HTTP CONNECT method ?  thks~

**Comment by railjty** [comment]
Test OK for me! It works very well now!

**Comment by chobits** [comment]
hi @wxy8435 

Could you show your nginx configure file?  

Also nginx debug log will be useful to resolve this problem, you can enable it via http://nginx.org/en/docs/debugging_log.html.

**Comment by wxy8435** [comment]
@chobits  thks for replay。直接用中文吧。
wifi直连情况下，curl -k   -v -x localhost:8888 -o index.html --progress-bar https://www.baidu.com/     这个就可以获取到页面。nginx貌似转发正常。

公司内网环境需要走代理，转发代理服务器就不行， 日志显示  connect 正常，但是
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

不知道 proxy_connect_address  这个参数是否 指代   connect 的请求转发的代理地址？
connect 成功以后，是创建了 http tunnel ？ 后续所有的请求都在这个tunnel中进行？
那示例配置forward proxy for non-CONNECT request   这个具体又是啥意思？其他的 GET,POST  就走proxy_pass  代理？  那为啥又是   http的转发呢？

我的配置：

    # HTTPS server
    #
    server {
        listen       8888 ;
        resolver 10.251.139.241    8.8.8.8  ;
        server_name  localhost;

        proxy_connect ;
        proxy_connect_allow  443 563;
        proxy_connect_connect_timeout  60s;
	      proxy_connect_read_timeout  60s;
	      proxy_connect_send_timeout  60s;
	      #proxy_connect_address  10.243.184.40:8081 ;---内网代理服务器地址，wifi下注释掉
	      proxy_connect_address  off; ----wifi下
	      proxy_connect_bind off;

	      
	      charset utf-8; 
	      	      
        #ssl_certificate      /usr/local/Cellar/openssl/1.0.2o_2/bin/cert.pem;
        #ssl_certificate_key  /usr/local/Cellar/openssl/1.0.2o_2/bin/cert.key;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
            
            proxy_set_header   Host     $host;            
            proxy_pass http://10.243.184.40:8081 ;----感觉这个 proxy_pass 不起作用，而且为啥是http？
            
            #proxy_set_header   X-Real-IP        $remote_addr;
            #proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
            #proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            #proxy_max_temp_file_size 0;

        }
    }#https server

**Comment by wxy8435** [comment]
内网重新测试下，

userdeMacBook-Air:~ user$ curl https://www.baidu.com/ -v -x localhost:8888 -o index.html --progress-bar -k
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8888 failed: Connection refused
*   Trying fe80::1...
* TCP_NODELAY set
* Connection failed
* connect to fe80::1 port 8888 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8888 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.baidu.com:443
> CONNECT www.baidu.com:443 HTTP/1.1
> Host: www.baidu.com:443
> User-Agent: curl/7.61.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection Established
< Proxy-agent: nginx
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: /usr/local/etc/openssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* CONNECT phase completed!
* CONNECT phase completed!
* error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
* Closing connection 0

curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

nginx日志没有明显错误。

2018/08/10 16:29:24 [debug] 20388#0: accept on 0.0.0.0:8888, ready: 1
2018/08/10 16:29:24 [debug] 20389#0: kevent events: 1
2018/08/10 16:29:24 [debug] 20389#0: kevent: 10: ft:-1 fl:0005 ff:00000000 d:1 ud:00007FAD24816C00
2018/08/10 16:29:24 [debug] 20389#0: accept on 0.0.0.0:8888, ready: 1
2018/08/10 16:29:24 [debug] 20388#0: posix_memalign: 00007FAD23F00160:512 @16
2018/08/10 16:29:24 [debug] 20389#0: accept() not ready (35: Resource temporarily unavailable)
2018/08/10 16:29:24 [debug] 20388#0: *58 accept: 127.0.0.1:59395 fd:4
2018/08/10 16:29:24 [debug] 20388#0: *58 event timer add: 4: 60000:22039878
2018/08/10 16:29:24 [debug] 20388#0: *58 reusable connection: 1
2018/08/10 16:29:24 [debug] 20388#0: *58 kevent set event: 4: ft:-1 fl:0025
2018/08/10 16:29:24 [debug] 20388#0: timer delta: 3266
2018/08/10 16:29:24 [debug] 20388#0: worker cycle
2018/08/10 16:29:24 [debug] 20388#0: kevent timer: 60000, changes: 1
2018/08/10 16:29:24 [debug] 20388#0: kevent events: 1
2018/08/10 16:29:24 [debug] 20388#0: kevent: 4: ft:-1 fl:0025 ff:00000000 d:118 ud:00007FAD25012AD0
2018/08/10 16:29:24 [debug] 20388#0: *58 http wait request handler
2018/08/10 16:29:24 [debug] 20388#0: *58 malloc: 00007FAD25004000:1024
2018/08/10 16:29:24 [debug] 20388#0: *58 recv: eof:0, avail:118, err:0
2018/08/10 16:29:24 [debug] 20388#0: *58 recv: fd:4 118 of 1024
2018/08/10 16:29:24 [debug] 20388#0: *58 reusable connection: 0
2018/08/10 16:29:24 [debug] 20388#0: *58 posix_memalign: 00007FAD25004400:4096 @16
2018/08/10 16:29:24 [debug] 20388#0: *58 http process request line
2018/08/10 16:29:24 [debug] 20388#0: *58 http request line: "CONNECT www.baidu.com:443 HTTP/1.1"
2018/08/10 16:29:24 [debug] 20388#0: *58 http uri: ""
2018/08/10 16:29:24 [debug] 20388#0: *58 http args: ""
2018/08/10 16:29:24 [debug] 20388#0: *58 http exten: ""
2018/08/10 16:29:24 [debug] 20388#0: *58 posix_memalign: 00007FAD25005400:4096 @16
2018/08/10 16:29:24 [debug] 20388#0: *58 http process request header line
2018/08/10 16:29:24 [debug] 20388#0: *58 http header: "Host: www.baidu.com:443"
2018/08/10 16:29:24 [debug] 20388#0: *58 http header: "User-Agent: curl/7.61.0"
2018/08/10 16:29:24 [debug] 20388#0: *58 http header: "Proxy-Connection: Keep-Alive"
2018/08/10 16:29:24 [debug] 20388#0: *58 http header done
2018/08/10 16:29:24 [debug] 20388#0: *58 event timer del: 4: 22039878
2018/08/10 16:29:24 [debug] 20388#0: *58 generic phase: 0
2018/08/10 16:29:24 [debug] 20388#0: *58 generic phase: 1
2018/08/10 16:29:24 [debug] 20388#0: *58 rewrite phase: 2
2018/08/10 16:29:24 [debug] 20388#0: *58 rewrite phase: 4
2018/08/10 16:29:24 [debug] 20388#0: *58 post rewrite phase: 5
2018/08/10 16:29:24 [debug] 20388#0: *58 generic phase: 6
2018/08/10 16:29:24 [debug] 20388#0: *58 generic phase: 7
2018/08/10 16:29:24 [debug] 20388#0: *58 generic phase: 8
2018/08/10 16:29:24 [debug] 20388#0: *58 generic phase: 9
2018/08/10 16:29:24 [debug] 20388#0: *58 access phase: 10
2018/08/10 16:29:24 [debug] 20388#0: *58 access phase: 11
2018/08/10 16:29:24 [debug] 20388#0: *58 access phase: 12
2018/08/10 16:29:24 [debug] 20388#0: *58 post access phase: 13
2018/08/10 16:29:24 [debug] 20388#0: *58 generic phase: 14
2018/08/10 16:29:24 [debug] 20388#0: *58 generic phase: 15
2018/08/10 16:29:24 [debug] 20388#0: *58 connect network address given by proxy_connect_address
2018/08/10 16:29:24 [debug] 20388#0: *58 stream socket 8
2018/08/10 16:29:24 [debug] 20388#0: *58 connect to 10.243.184.40:8081, fd:8 #59
2018/08/10 16:29:24 [debug] 20387#0: kevent events: 1
2018/08/10 16:29:24 [debug] 20387#0: kevent: 10: ft:-1 fl:0005 ff:00000000 d:1 ud:00007FAD25012A00
2018/08/10 16:29:24 [debug] 20387#0: accept on 0.0.0.0:8888, ready: 1
2018/08/10 16:29:24 [debug] 20387#0: accept() not ready (35: Resource temporarily unavailable)
2018/08/10 16:29:24 [debug] 20387#0: timer delta: 3266
2018/08/10 16:29:24 [debug] 20387#0: worker cycle
2018/08/10 16:29:24 [debug] 20387#0: kevent timer: -1, changes: 0
2018/08/10 16:29:24 [debug] 20390#0: kevent events: 1
2018/08/10 16:29:24 [debug] 20388#0: *58 kevent set event: 8: ft:-1 fl:0025
2018/08/10 16:29:24 [debug] 20390#0: kevent: 10: ft:-1 fl:0005 ff:00000000 d:1 ud:00007FAD25012A00
2018/08/10 16:29:24 [debug] 20389#0: timer delta: 3266
2018/08/10 16:29:24 [debug] 20390#0: accept on 0.0.0.0:8888, ready: 1
2018/08/10 16:29:24 [debug] 20391#0: accept on 0.0.0.0:8888, ready: 1
2018/08/10 16:29:24 [debug] 20390#0: accept() not ready (35: Resource temporarily unavailable)
2018/08/10 16:29:24 [debug] 20390#0: timer delta: 3266
2018/08/10 16:29:24 [debug] 20388#0: *58 kevent set event: 8: ft:-2 fl:0025
2018/08/10 16:29:24 [debug] 20388#0: *58 proxy_connect upstream connect: -2
2018/08/10 16:29:24 [debug] 20388#0: *58 posix_memalign: 00007FAD23D0B860:128 @16
2018/08/10 16:29:24 [debug] 20388#0: *58 event timer add: 8: 60000:22039879
2018/08/10 16:29:24 [debug] 20388#0: *58 http finalize request: -4, "?" a:1, c:2
2018/08/10 16:29:24 [debug] 20388#0: *58 http request count:2 blk:0
2018/08/10 16:29:24 [debug] 20388#0: timer delta: 1
2018/08/10 16:29:24 [debug] 20388#0: worker cycle
2018/08/10 16:29:24 [debug] 20388#0: kevent timer: 60000, changes: 2
2018/08/10 16:29:24 [debug] 20391#0: accept() not ready (35: Resource temporarily unavailable)
2018/08/10 16:29:24 [debug] 20391#0: timer delta: 3266
2018/08/10 16:29:24 [debug] 20391#0: worker cycle
2018/08/10 16:29:24 [debug] 20391#0: kevent timer: -1, changes: 0
2018/08/10 16:29:24 [debug] 20390#0: worker cycle
2018/08/10 16:29:24 [debug] 20390#0: kevent timer: -1, changes: 0
2018/08/10 16:29:24 [debug] 20389#0: worker cycle
2018/08/10 16:29:24 [debug] 20389#0: kevent timer: -1, changes: 0
2018/08/10 16:29:24 [debug] 20388#0: kevent events: 1
2018/08/10 16:29:24 [debug] 20388#0: kevent: 8: ft:-2 fl:0025 ff:00000000 d:131328 ud:00007FAD25040B38
2018/08/10 16:29:24 [debug] 20388#0: *58 http proxy_connect upstream handler: "www.baidu.com:443"
2018/08/10 16:29:24 [debug] 20388#0: *58 proxy_connect upstream write handler
2018/08/10 16:29:24 [debug] 20388#0: *58 event timer del: 8: 22039879
2018/08/10 16:29:24 [debug] 20388#0: *58 proxy_connect send 200 connection estatbilshed
2018/08/10 16:29:24 [debug] 20388#0: *58 send: fd:4 59 of 59
2018/08/10 16:29:24 [debug] 20388#0: *58 proxy_connect sent 200 connection estatbilshed
2018/08/10 16:29:24 [debug] 20388#0: timer delta: 6
2018/08/10 16:29:24 [debug] 20388#0: worker cycle
2018/08/10 16:29:24 [debug] 20388#0: kevent timer: -1, changes: 0
2018/08/10 16:29:24 [debug] 20388#0: kevent events: 1
2018/08/10 16:29:24 [debug] 20388#0: kevent: 4: ft:-1 fl:0025 ff:00000000 d:517 ud:00007FAD25012AD0
2018/08/10 16:29:24 [debug] 20388#0: *58 http run request: "?"
2018/08/10 16:29:24 [debug] 20388#0: *58 http proxy_connect, fu:0 write:0
2018/08/10 16:29:24 [debug] 20388#0: *58 malloc: 00007FAD25801800:16384
2018/08/10 16:29:24 [debug] 20388#0: *58 recv: eof:0, avail:517, err:0
2018/08/10 16:29:24 [debug] 20388#0: *58 recv: fd:4 517 of 16384
2018/08/10 16:29:24 [debug] 20388#0: *58 send: fd:8 517 of 517
2018/08/10 16:29:24 [debug] 20388#0: *58 event timer add: 4: 60000:22039887
2018/08/10 16:29:24 [debug] 20388#0: timer delta: 2
2018/08/10 16:29:24 [debug] 20388#0: worker cycle
2018/08/10 16:29:24 [debug] 20388#0: kevent timer: 60000, changes: 0
2018/08/10 16:29:24 [debug] 20388#0: kevent events: 1
2018/08/10 16:29:24 [debug] 20388#0: kevent: 8: ft:-2 fl:0025 ff:00000000 d:131328 ud:00007FAD25040B38
2018/08/10 16:29:24 [debug] 20388#0: *58 http proxy_connect upstream handler: "www.baidu.com:443"
2018/08/10 16:29:24 [debug] 20388#0: *58 proxy_connect upstream write handler
2018/08/10 16:29:24 [debug] 20388#0: *58 http proxy_connect, fu:0 write:1
2018/08/10 16:29:24 [debug] 20388#0: *58 event timer: 4, old: 22039887, new: 22039892
2018/08/10 16:29:24 [debug] 20388#0: timer delta: 5
2018/08/10 16:29:24 [debug] 20388#0: worker cycle
2018/08/10 16:29:24 [debug] 20388#0: kevent timer: 59995, changes: 0
2018/08/10 16:29:24 [debug] 20388#0: kevent events: 1
2018/08/10 16:29:24 [debug] 20388#0: kevent: 8: ft:-1 fl:0025 ff:00000000 d:903 ud:00007FAD25012B38
2018/08/10 16:29:24 [debug] 20388#0: *58 http proxy_connect upstream handler: "www.baidu.com:443"
2018/08/10 16:29:24 [debug] 20388#0: *58 proxy_connect upstream read handler
2018/08/10 16:29:24 [debug] 20388#0: *58 malloc: 00007FAD25006400:16384
2018/08/10 16:29:24 [debug] 20388#0: *58 http proxy_connect, fu:1 write:0
2018/08/10 16:29:24 [debug] 20388#0: *58 recv: eof:0, avail:903, err:0
2018/08/10 16:29:24 [debug] 20388#0: *58 recv: fd:8 903 of 16384
2018/08/10 16:29:24 [debug] 20388#0: *58 send: fd:4 903 of 903
2018/08/10 16:29:24 [debug] 20388#0: *58 event timer add: 8: 60000:22039892
2018/08/10 16:29:24 [debug] 20388#0: timer delta: 0
2018/08/10 16:29:24 [debug] 20388#0: worker cycle
2018/08/10 16:29:24 [debug] 20388#0: kevent timer: 59995, changes: 0
2018/08/10 16:29:24 [debug] 20388#0: kevent events: 1
2018/08/10 16:29:24 [debug] 20388#0: kevent: 8: ft:-1 fl:8025 ff:00000000 d:0 ud:00007FAD25012B38
2018/08/10 16:29:24 [debug] 20388#0: *58 http proxy_connect upstream handler: "www.baidu.com:443"
2018/08/10 16:29:24 [debug] 20388#0: *58 proxy_connect upstream read handler
2018/08/10 16:29:24 [debug] 20388#0: *58 http proxy_connect, fu:1 write:0
2018/08/10 16:29:24 [debug] 20388#0: *58 recv: eof:1, avail:0, err:0
2018/08/10 16:29:24 [debug] 20388#0: *58 http proxy_connect done
2018/08/10 16:29:24 [debug] 20388#0: *58 finalize proxy_conncet upstream request: 0
2018/08/10 16:29:24 [debug] 20388#0: *58 close proxy_connect upstream connection: 8
2018/08/10 16:29:24 [debug] 20388#0: *58 free: 00007FAD23D0B860, unused: 48
2018/08/10 16:29:24 [debug] 20388#0: *58 event timer del: 8: 22039892
2018/08/10 16:29:24 [debug] 20388#0: *58 reusable connection: 0
2018/08/10 16:29:24 [debug] 20388#0: *58 http finalize request: 0, "?" a:1, c:1
2018/08/10 16:29:24 [debug] 20388#0: *58 event timer del: 4: 22039887
2018/08/10 16:29:24 [debug] 20388#0: *58 http request count:1 blk:0
2018/08/10 16:29:24 [debug] 20388#0: *58 http close request
2018/08/10 16:29:24 [debug] 20388#0: *58 http log handler
2018/08/10 16:29:24 [debug] 20388#0: *58 free: 00007FAD25006400
2018/08/10 16:29:24 [debug] 20388#0: *58 free: 00007FAD25801800
2018/08/10 16:29:24 [debug] 20388#0: *58 free: 00007FAD25004400, unused: 8
2018/08/10 16:29:24 [debug] 20388#0: *58 free: 00007FAD25005400, unused: 2843
2018/08/10 16:29:24 [debug] 20388#0: *58 close http connection: 4
2018/08/10 16:29:24 [debug] 20388#0: *58 reusable connection: 0
2018/08/10 16:29:24 [debug] 20388#0: *58 free: 00007FAD25004000
2018/08/10 16:29:24 [debug] 20388#0: *58 free: 00007FAD23F00160, unused: 136
2018/08/10 16:29:24 [debug] 20388#0: timer delta: 1
2018/08/10 16:29:24 [debug] 20388#0: worker cycle
2018/08/10 16:29:24 [debug] 20388#0: kevent timer: -1, changes: 0

==> access.log <==
127.0.0.1 -  [10/Aug/2018:16:29:24 +0800] "CONNECT www.baidu.com:443 HTTP/1.1" 000 962 "" "curl/7.61.0" ""

**Comment by chobits** [comment]
hi @wxy8435
