### ISSUE TITLE
compilation error: 'ngx_http_request_t {aka struct ngx_http_request_s}' has no member named 'connect_port_n

### ISSUE THREAD

**Issue by mclite** [chobits/ngx_http_proxy_connect_module#56]
Here is my docker file. This does not seem to work on the nginx visted below or the one in the install docs

COPY ./ngx_http_proxy_connect_module /ngx_http_proxy_connect_module
RUN apk update --no-cache
RUN apk add --no-cache git openssh make gcc openssl-dev pcre-dev zlib-dev wget build-base
RUN wget http://nginx.org/download/nginx-1.15.2.tar.gz
RUN tar -xzvf nginx-1.15.2.tar.gz
RUN cd nginx-1.15.2/ && patch -p1 /ngx_http_proxy_connect_module/patch/proxy_connect.patch && ./configure --add-module=/ngx_http_proxy_connect_module && make && make install

ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c: In function 'ngx_http_proxy_connect_handler':
/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1350:39: error: 'ngx_http_request_t {aka struct ngx_http_request_s}' has no member named 'connect_port_n'; did you mean 'connection'?
             if ((ports[i][1] == 0 && r->connect_port_n == ports[i][0])
                                       ^~

**Comment by chobits** [comment]
Hi @mclite 

Thanks for your report, this problem is be solved now in https://github.com/chobits/ngx_http_proxy_connect_module/issues/55.

**Comment by chobits** [comment]
Any status changing will be updated in https://github.com/chobits/ngx_http_proxy_connect_module/issues/55.

I think this problem will be fixed soon:)

**Comment by mclite** [comment]
Awesome!! Thanks for the quick turn around.

**Comment by chobits** [comment]
Hi all,

This module has supported nginx-1.15.x (current mainline version nginx-1.15.1~nginx.1.15.2). You can check lastest master branch. For the detail of development, see https://github.com/chobits/ngx_http_proxy_connect_module/pull/60.

`NOTE`: make sure that you use new patch & new module source together. I have refactored patch & module source in this pr [#59: simplify patch: move CONNECT request checking logic to module source](https://github.com/chobits/ngx_http_proxy_connect_module/pull/59).

**Comment by chobits** [comment]
think it resolved. Feel free to reopen / comment if you still have this problem.
