### ISSUE TITLE
ssl how to configure？

### ISSUE THREAD

**Issue by duanxg** [chobits/ngx_http_proxy_connect_module#6]
ssl how to configure？
my configuration does not work？

**Comment by chobits** [comment]
Hi @duanxg 

Can u give more details of what u want to do?

If u wanna proxy SSL request with CONNECT method (http connect tunnel), there is a simple configure in README ( see [here](https://github.com/chobits/ngx_http_proxy_connect_module#example)).

**Comment by duanxg** [comment]
@chobits I have solved this problem
