### ISSUE TITLE
transparent proxying is not supported on this platform

### ISSUE THREAD

**Issue by peettee** [chobits/ngx_http_proxy_connect_module#63]
Hi at first thank you for this module.

I have an issue when attempting to forward the actual client IP-Adress to my proxied Application.
I use the following configuration to enable CONNECT proxying on my default server configuration:

```
proxy_connect;
proxy_connect_allow            25568 25570;
proxy_connect_connect_timeout  10s;
proxy_connect_read_timeout     10s;
proxy_connect_send_timeout     10s;
proxy_connect_bind $remote_addr transparent;
```

Whenever I add the proxy_connect_bind entry and do reload the config using `nginx -s reload` I get the following output: 

`nginx:  [emerg] transparent proxying is not supported on this platform, ignored in /etc/nginx/sites-enabled/default:47`

I am using: `nginx version: nginx/1.6.2`.

When I omit the "transparent" parameter from the proxy_connect_bind entry I get an internal Server error (500) response on the client side and the following output in my nginx error.log:

2018/09/04 15:53:57 [crit] 25341#0: *2287 bind([MY_IP]) failed (99: Cannot assign requested address) while connecting to upstream(proxy_connect), client: [MY_IP], server: [TARGET_URL], request: "CONNECT [TARGET_URL]:25568 HTTP/1.0"

Thanks in advance for any insights.

**Comment by chobits** [comment]
```
nginx: [emerg] transparent proxying is not supported on this platform, ignored in /etc/nginx/sites-enabled/default:47
```

This means IP_TRANSPARENT is not supported on your platform. From [linux ip (7) manual](http://man7.org/linux/man-pages/man7/ip.7.html), this option is supported since Linux 2.6.24.

**Comment by chobits** [comment]
Linux kernel documentation about transparent proxy, see https://www.kernel.org/doc/Documentation/networking/tproxy.txt.

**Comment by chobits** [comment]
How nginx configure check your platform supports this option, see nginx-source/auto/unix:

```
# OpenBSD bind to any address for transparent proxying

ngx_feature="SO_BINDANY"
ngx_feature_name="NGX_HAVE_TRANSPARENT_PROXY"
ngx_feature_run=no
ngx_feature_incs="#include <sys/socket.h>"
ngx_feature_path=
ngx_feature_libs=
ngx_feature_test="setsockopt(0, SOL_SOCKET, SO_BINDANY, NULL, 0)"
. auto/feature


# Linux transparent proxying

ngx_feature="IP_TRANSPARENT"
ngx_feature_name="NGX_HAVE_TRANSPARENT_PROXY"
ngx_feature_run=no
ngx_feature_incs="#include <sys/socket.h>
                  #include <netinet/in.h>"
ngx_feature_path=
ngx_feature_libs=
ngx_feature_test="setsockopt(0, IPPROTO_IP, IP_TRANSPARENT, NULL, 0)"
. auto/feature


# FreeBSD bind to any address for transparent proxying

ngx_feature="IP_BINDANY"
ngx_feature_name="NGX_HAVE_TRANSPARENT_PROXY"
ngx_feature_run=no
ngx_feature_incs="#include <sys/socket.h>
                  #include <netinet/in.h>"
ngx_feature_path=
ngx_feature_libs=
ngx_feature_test="setsockopt(0, IPPROTO_IP, IP_BINDANY, NULL, 0)"
. auto/feature
```

**Comment by peettee** [comment]
Output of "uname -a" is: `Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux`. My kernel should support transparent proxying.

I did however update my nginx installation to version 1.15.2. Now the "transparent proxying is not supported on this platform" Message is no longer displayed and I can reload my configuration. After telling nginx to use root as its default user, the bind to the clients IP-Address seems to be successful.

But no response is received after connecting through nginx to my backend service. The connection just times out after a while. No error (actually no message at all) is displayed in the nginx log files. 
No `[IP] - - [05/Sep/2018:13:07:57 +0200] "CONNECT [TARGET_HOST]:25570 HTTP/1.0" 000 2601 "-" "-"` message is displayed in the nginx log as It would when I disable the proxy_connect_bind entry.

Do I have to configure my iptables as described in the linux kernel doc about transparent proxies?

**Comment by chobits** [comment]
> But no response is received after connecting through nginx to my backend service. The connection just times out after a while. No error (actually no message at all) is displayed in the nginx log files.
No [IP] - - [05/Sep/2018:13:07:57 +0200] "CONNECT [TARGET_HOST]:25570 HTTP/1.0" 000 2601 "-" "-" message is displayed in the nginx log as It would when I disable the proxy_connect_bind entry.

* How does your client request nginx(proxy_connect)?
* also see logs/error.log to check whether there is error message.
* if you can give [debug log](http://nginx.org/en/docs/debugging_log.html), it makes resolving this issue easy.

> Do I have to configure my iptables as described in the linux kernel doc about transparent proxies?
If you dont need transparent-remote-address feature, you dont not need to configure iptable.

**Comment by chobits** [comment]
think it resolved, feel free to reopen if you have any problem.

**Comment by liudianwei** [comment]
Has this problem been solved
