### ISSUE TITLE
unexpected requests in log

### ISSUE THREAD

**Issue by PaulOnion** [chobits/ngx_http_proxy_connect_module#65]
Hi!
This is part of access.log
85.97.129.80 - - [21/Sep/2018:19:03:35 +0800] "GET / HTTP/1.1" 200 612 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
116.212.150.49 - - [21/Sep/2018:20:41:54 +0800] "GET / HTTP/1.1" 200 612 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
60.191.38.78 - - [21/Sep/2018:20:45:01 +0800] "GET / HTTP/1.1" 200 612 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0"
79.120.133.202 - - [21/Sep/2018:20:53:26 +0800] "GET / HTTP/1.1" 200 612 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
46.153.21.60 - - [21/Sep/2018:21:27:10 +0800] "GET / HTTP/1.1" 200 612 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"

I have never sent a request from these ips. And,I set auth_basic_user_file, But these requests still exist.

**Comment by chobits** [comment]
Could you post your configuration?

**Comment by PaulOnion** [comment]
Hello this is my profile
# right_proxy.conf
server {
     listen                         3128;

     # dns resolver used by forward proxying
     resolver                       8.8.8.8;

     # forward proxy for CONNECT request
     proxy_connect;
     proxy_connect_allow            443 563;
     proxy_connect_connect_timeout  10s;
     proxy_connect_read_timeout     10s;
     proxy_connect_send_timeout     10s;

     # forward proxy for non-CONNECT request
     location / {
         proxy_pass http://$host;
         proxy_set_header Host $host;
         
         proxy_buffers 256 4k;
         proxy_max_temp_file_size 0;
         proxy_connect_timeout 30;         

         auth_basic "Please enter your password";
         auth_basic_user_file /usr/local/nginx/conf/htpasswd;
     }
}

**Comment by PaulOnion** [comment]
First,thanks for your help. I`m so sorry. I have deleted the information about the nginx module before. I used this module again today, using the same configuration. But, I didn`t find an unusual request this time, and user authentication only appears on some pages. I think the big probability should be my own problem.
    I don`think I should use nginx as a forward proxy. I have used other tools to do forward proxy.
Thanks for your help again. This is a good module, thank you for your contribution.

**Comment by PaulOnion** [comment]
for example
"https://www.baidu.com" is a https request, When I use proxy access, I am not asked to enter a username and password.
"http://ip.6655.com/ip.aspx" is a http request, When I use proxy access, I am asked to enter a username and password

**Comment by PaulOnion** [comment]
Add, I use Alibaba Cloud Server

**Comment by chobits** [comment]
think it resolved, feel free to reopen if you have any problem.
