### ISSUE TITLE
Rebuild NGINX 1.13.9 add module ngx_http_proxy_connect_module 

### ISSUE THREAD

**Issue by szbaby1221** [chobits/ngx_http_proxy_connect_module#66]
Hi,
This pach solved my problem which nginx not support forward Proxy https.
But new problem occur. After rebuild i cant visit https form internet for reverse proxy .
Forward Proxy
Private network => intranet to Internet (http https)OK
Reverse Proxy => Internet to intranet (http OK) , but https is error

thanks a lot 

#25769902144: *4 upstream timed out (116: Connection timed out)

```
--Reverse proxy


server {
listen 443 ssl;
server_name xxxx.com;
ssl_certificate xxxxx.pem;
ssl_certificate_key xxxxx.key;
ssl_session_timeout 5m;
ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_prefer_server_ciphers on;

charset utf-8;
#charset koi8-r;

# access_log off;

location / {
index index.aspx index.html index.htm;
proxy_buffer_size 64k;
proxy_buffers 32 32k;
proxy_busy_buffers_size 128k;
proxy_connect_timeout 600;
proxy_read_timeout 600;
proxy_send_timeout 600;

client_max_body_size 100m;
# proxy_pass http://myServer;
proxy_pass http://xxxxx;

proxy_set_header Host "xxxxx";
}
}
--Forward Proxy
server {
listen 8889;
# dns resolver used by forward proxying
resolver 114.114.114.114 8.8.8.8;
# forward proxy for CONNECT request
proxy_connect;
proxy_connect_allow 443 563 8889 3128;
proxy_connect_connect_timeout 10s;
proxy_connect_read_timeout 10s;
proxy_connect_send_timeout 10s;

large_client_header_buffers 4 16k;
client_max_body_size 300m;
client_body_buffer_size 128k;
proxy_connect_timeout 600;
proxy_read_timeout 600;
proxy_send_timeout 600;
proxy_buffer_size 64k;
proxy_buffers 4 32k;
proxy_busy_buffers_size 64k;
proxy_temp_file_write_size 64k;

# forward proxy for non-CONNECT request
location ^~/proxy_path/ {
proxy_pass http://$host;
proxy_set_header Host $host:$proxy_port;
proxy_set_header X-Real-IP $remote_addr;
#proxy_set_header X-Forwarded-For $remote_addr;

proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

}
}
```

**Comment by szbaby1221** [comment]
delete

**Comment by szbaby1221** [comment]
-

**Comment by szbaby1221** [comment]
英文有点表述不当
使用目的,公司 的网络只对NGSever 开了公网反问权限, 其余不通
反向
公网 => NGServer =>应用服务器
 =>正向
应用服务器=> NgServer =>公网

NGINX 1.13.9 官方 下载windows版本.
正常可以做饭向代理器  
Internet Client  = >Nginx Server  (Http Https)=> 内部Application Server
然而 Application Server 不能访问公网
重新编译添加装功能补丁后 解决了正向代理服务器
内部Application Server=> IE代理 = > Nginx Server  => Internet 
新的问题
之前正常的反向代理功能 https 没有反应了
用curl 测试后 http 正常有反应的
curl 测试后 https 在验证完证书后 就没有反应了.Nginx也没有任何反应.
过大概2分钟后,日志显示#25769902144: *4 upstream timed out (116: Connection timed out)

因为对原理不清楚, 不知道到底什么原因导致了这样的问题

**Comment by chobits** [comment]
问题描述不太清晰，无法搞清楚你的问题。

> 用curl 测试后 http 正常有反应的
> curl 测试后 https 在验证完证书后 就没有反应了.Nginx也没有任何反应.

curl的具体命令是什么

**Comment by szbaby1221** [comment]
我的NGINX Server 同一台主机 反向代理和正向代理
用编译过后的NGINX  出现了 反向的https无法访问, http正常的

目前我临时用两个NGINX 的服务解决这个问题,但不知道根本原因是什么
