### ISSUE TITLE
iptables+nginx做透明代理有问题 // cannot work for proxing on iptables+nginx

### ISSUE THREAD

**Issue by toadzhou** [chobits/ngx_http_proxy_connect_module#71]
iptables -t nat -A PREROUTING -i eth0 -p tcp -s 192.168.2.0/24 --dport 80 -j DNAT --to  192.168.2.116:3128 
iptables -t nat -A PREROUTING -i eth0 -p tcp -s 192.168.2.0/24 --dport 443 -j DNAT --to 192.168.2.116:3128

下面的机器直接`curl -x 192.168.2.116:3128 https://www.baidu.com `这样是没问题的，但在做完透明代理 直接访问的时候就有问题。是我哪里设置的不对吗？

**Comment by chobits** [comment]
请求求抱请求是否到达ngx_http_proxy_connect_module，我这里因为个人关系没法亲自配置iptables的问题，请确保先查看是否是该模块问题还是iptables问题。
