### ISSUE TITLE
Connection timed out errors

### ISSUE THREAD

**Issue by jlyonsmith** [chobits/ngx_http_proxy_connect_module#72]
I'm getting:

```
2019/01/17 21:38:32 [error] 4213#4213: *12683 upstream timed out (110: Connection timed out) while connecting to upstream(proxy_connect), client: 192.168.0.138, server: , request: "CONNECT registry.npmjs.org:443 HTTP/1.1", host: "registry.npmjs.org"
```

When trying to do an `npm install` through the proxy.  What happens is, I will get may a hundred or so successful upstream connections, and then this error will start to appear and `npm` will never recover.  

Both my systems are on AWS EC2.  My `nginx.conf` file looks like this:

```
worker_processes 1;

error_log /var/log/nginx/error.log info;

pid /run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include mime.types;
  default_type application/octet-stream;
  sendfile on;
  keepalive_timeout 65;

  server {
    listen 3128;
    resolver 127.0.0.53 ipv6=off;
    resolver_timeout 30s;

    # Forward proxy for CONNECT requests
    proxy_connect;
    proxy_connect_allow 443;
    proxy_connect_connect_timeout 30s;
    proxy_connect_read_timeout 30s;
    proxy_connect_send_timeout 30s;

    # Forward proxy for non-CONNECT request
    location / {
      proxy_pass http://$host;
      proxy_set_header Host $host;
    }
  }
}
```

I found I had to add the `ipv6=off` or the I'd get this error almost constantly.  Apparently there is a race condition with the DNS server sometimes returning an IPv6 record before the IPv4 one.

**Comment by chobits** [comment]
> 2019/01/17 21:38:32 [error] 4213#4213: *12683 upstream timed out (110: Connection timed out) while connecting to upstream(proxy_connect), client: 192.168.0.138, server: , request: "CONNECT registry.npmjs.org:443 HTTP/1.1", host: "registry.npmjs.org"

This means proxy_connect module tried to connect backend peer and it timed out finally. The backend peer is returned by DNS server for resolving registry.npmjs.org.

Based on what you said about IPv6 resolving, I guess your proxy server cannot connect to the IPv6 peer address.

But it is hard to fixed in proxy_connect module, proxy_connect module just calls standard nginx-core DNS API.

BTW, I'll optimize the error log to show timedout IP address.

**Comment by chobits** [comment]
* TODO: optimize error log to show  connect-timedout IP address

**Comment by bigboyq** [comment]
I have solved similar problem by adding 
```
proxy_connect_timeout 600;
proxy_send_timeout 600;
proxy_read_timeout 600;
send_timeout 600;
```
in nginx.conf, just have a try

**Comment by jrgp** [comment]
Hi @chobits do you have an update on this?

I'm seeing something similar: I see a bunch of these upstream timeout errors in logs, but in the access log they don't always show up as 504s. Do you have any ideas as to the disparity between the error logs and the access logs for these timeouts?

**Comment by chobits** [comment]
> Hi @chobits do you have an update on this?
> 
> I'm seeing something similar: I see a bunch of these upstream timeout errors in logs, but in the access log they don't always show up as 504s. Do you have any ideas as to the disparity between the error logs and the access logs for these timeouts? I'm wondering if the proxy module tries to reconnect a few times before giving up.

Response status will be 200 not 504 if CONNECT tunnel has been established with backend server and then the timedout error occurs.

Will modify some error message to show these details.

**Comment by chobits** [comment]
hi @jrgp 

> Im wondering if the proxy module tries to reconnect a few times before giving up.

No, proxy_connect modules does not reconnect a few times. 
And note that only error message including `proxy_connect` string is generated by proxy_connect, other error messages may be generated by nginx upstream(http proxy).

**Comment by chobits** [comment]
Error log messages has been updated in https://github.com/chobits/ngx_http_proxy_connect_module/pull/121.

For doc of error log message, see [readme/error log](https://github.com/chobits/ngx_http_proxy_connect_module#error-log)

**Comment by jlyonsmith** [comment]
Just as an additional data point, we switched to using Tengine instead of vanilla `nginx` and have not seen this issue.  @chobits It is my understanding that you merged this module into Tengine.  Is there something different about it in the Tengine code base?  With this module and nginx we would see this timeout error downloading `npm` modules regularly.  We have never seen with Tengine.

**Comment by chobits** [comment]
hi @jlyonsmith 

>  It is my understanding that you merged this module into Tengine. 

Yes

> Is there something different about it in the Tengine code base?

Tengine core base has something different about nginx. However, proxy_connect module code base has nothing diffrerent with them.  Hard to explain the diffrence.

Maybe new [error log messages](https://github.com/chobits/ngx_http_proxy_connect_module#error-log) can help to locate this problem. It shows backend address and dispart connect/read syscall.

**Comment by jrgp** [comment]
Hi @chobits thanks for adding the additional debugging messages. I just upgraded to the latest master rev and I'm now seeing the additional information, with the error classified as a read timeout:

    2019/08/08 19:10:05 [error] 11765#0: *471838 proxy_connect: upstream read timed out (peer:[REDACTED]:443) while connecting to upstream, client: REDACTED, server: , request: "CONNECT REDACTED:443 HTTP/1.1", host: "REDACTED:443"

I'm using nginx 1.12.2. Do you think there are improvements in the nginx core between 1.12.2 and 1.16.0 which could help this problem, or is it more likely to be a networking/config problem on my end?

Also, are the proxy timeout config options in vanilla nginx relevant here or do only the `proxy_connect_*` options this module provides matter?

**Comment by chobits** [comment]
> Also, are the proxy timeout config options in vanilla nginx relevant here or do only the proxy_connect_* options this module provides matter?

For backend timeout, `proxy_connect_*` works.

**Comment by chobits** [comment]
hi @jrgp 

> proxy_connect:  upstream read timed out

It means  proxy_connect tries to read data from backend server, but the backend server does not send data back during timeout set by [`proxy_connect_read_timeout`](https://github.com/chobits/ngx_http_proxy_connect_module#proxy_connect_read_timeout) occurs. Try to increase the value of timeout.

**Comment by jrgp** [comment]
Hi @chobits. Thanks for the info. Bumping that setting much higher (30s to 60s) made most of the error messages go away. Now I need to determine why the timeout needs to be set so high :)

**Comment by chobits** [comment]
Hi all, I'm closing this issue, because this TODO item (error log optimization) has been completed.

---

If still having some issues about error_log, you can comment on this thread.  
For other questions, feel free to open a new issue.

**Comment by koalabearguo** [comment]
hello,how can I reslove this problem?now i ,meet the same issus
----------------------------------------------------------------------
nginx/1.16.1
----------------------------------------------------------------------
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
error_log /var/log/nginx/debug.log debug;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;
#load_module /usr/local/nginx/modules/ngx_http_proxy_connect_module.so;
events {
    worker_connections 1024;
}
http {
server {
    listen      127.0.0.1:80;
    server_name  localhost;
    resolver       127.0.0.1 ipv6=off;
    resolver_timeout 5s;

    # forward proxy for CONNECT request
    proxy_connect;
    proxy_connect_allow            all;
    proxy_connect_connect_timeout  600s;
    proxy_connect_read_timeout     600s;
    proxy_connect_send_timeout     600s;

    proxy_connect_timeout 600s;
    proxy_send_timeout 600s;
    proxy_read_timeout 600s;
    send_timeout 600s;

    #include conf.d/ip_allow.ini;
    auth_basic  "secret";   #添加此配置
    auth_basic_user_file  /etc/squid/passwd; #加载生成的密码文件

    # forward proxy for non-CONNECT request
    location / {
	    #proxy_pass http://127.0.0.1:3128;
	    # these two lines here            
            #proxy_http_version 1.1;
            #proxy_set_header Connection "";

	    proxy_pass http://$http_host;
            proxy_set_header Host $host:$http_host;
    }
}
}

----------------------------------------------------------------------
2021/04/15 02:35:11 [error] 965#0: *143 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT ogs.google.com:443 HTTP/1.1", host: "ogs.google.com:443"
2021/04/15 02:35:13 [error] 965#0: *145 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT apis.google.com:443 HTTP/1.1", host: "apis.google.com:443"
2021/04/15 02:35:17 [error] 964#0: *137 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT adservice.google.com:443 HTTP/1.1", host: "adservice.google.com:443"
2021/04/15 02:35:17 [error] 964#0: *127 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT www.google.com:443 HTTP/1.1", host: "www.google.com:443"
2021/04/15 02:35:18 [error] 965#0: *153 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT github.com:443 HTTP/1.1", host: "github.com:443"
2021/04/15 02:35:20 [error] 965#0: *161 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT github.githubassets.com:443 HTTP/1.1", host: "github.githubassets.com:443"
2021/04/15 02:35:20 [error] 965#0: *155 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT github.githubassets.com:443 HTTP/1.1", host: "github.githubassets.com:443"
2021/04/15 02:35:22 [error] 964#0: *141 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT ogs.google.com:443 HTTP/1.1", host: "ogs.google.com:443"
2021/04/15 02:35:22 [error] 964#0: *45 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT play.google.com:443 HTTP/1.1", host: "play.google.com:443"
2021/04/15 02:35:23 [error] 964#0: *147 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT github.githubassets.com:443 HTTP/1.1", host: "github.githubassets.com:443"
2021/04/15 02:35:27 [error] 965#0: *111 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT beacons.gcp.gvt2.com:443 HTTP/1.1", host: "beacons.gcp.gvt2.com:443"
2021/04/15 02:35:27 [error] 965#0: *169 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT google.com:443 HTTP/1.1", host: "google.com:443"
2021/04/15 02:35:27 [error] 964#0: *167 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT google.com:443 HTTP/1.1", host: "google.com:443"
2021/04/15 02:35:47 [error] 964#0: *173 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT content-autofill.googleapis.com:443 HTTP/1.1", host: "content-autofill.googleapis.com:443"
2021/04/15 02:35:47 [error] 965#0: *171 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT content-autofill.googleapis.com:443 HTTP/1.1", host: "content-autofill.googleapis.com:443"
2021/04/15 02:37:08 [error] 965#0: *181 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT content-autofill.googleapis.com:443 HTTP/1.1", host: "content-autofill.googleapis.com:443"
2021/04/15 02:37:08 [error] 964#0: *179 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT content-autofill.googleapis.com:443 HTTP/1.1", host: "content-autofill.googleapis.com:443"
2021/04/15 02:37:20 [error] 965#0: *149 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT avatars.githubusercontent.com:443 HTTP/1.1", host: "avatars.githubusercontent.com:443"
2021/04/15 02:37:20 [error] 964#0: *185 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT beacons.gcp.gvt2.com:443 HTTP/1.1", host: "beacons.gcp.gvt2.com:443"
2021/04/15 02:37:20 [error] 965#0: *183 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT beacons.gcp.gvt2.com:443 HTTP/1.1", host: "beacons.gcp.gvt2.com:443"
2021/04/15 02:38:25 [error] 964#0: *191 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT beacons.gcp.gvt2.com:443 HTTP/1.1", host: "beacons.gcp.gvt2.com:443"
2021/04/15 02:38:53 [error] 965#0: *195 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT avatars.githubusercontent.com:443 HTTP/1.1", host: "avatars.githubusercontent.com:443"
2021/04/15 02:39:03 [error] 964#0: *193 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT avatars.githubusercontent.com:443 HTTP/1.1", host: "avatars.githubusercontent.com:443"
2021/04/15 02:39:21 [error] 964#0: *151 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT github.com:443 HTTP/1.1", host: "github.com:443"
2021/04/15 02:40:24 [error] 964#0: *199 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT play.google.com:443 HTTP/1.1", host: "play.google.com:443"
2021/04/15 02:40:24 [error] 965#0: *187 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT beacons.gcp.gvt2.com:443 HTTP/1.1", host: "beacons.gcp.gvt2.com:443"
2021/04/15 02:40:24 [error] 965#0: *197 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT play.google.com:443 HTTP/1.1", host: "play.google.com:443"
2021/04/15 02:41:27 [error] 965#0: *205 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT beacons.gcp.gvt2.com:443 HTTP/1.1", host: "beacons.gcp.gvt2.com:443"
2021/04/15 02:41:27 [error] 964#0: *202 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT beacons.gcp.gvt2.com:443 HTTP/1.1", host: "beacons.gcp.gvt2.com:443"
2021/04/15 02:44:28 [error] 964#0: *209 proxy_connect: client read timed out while connecting to upstream, client: 127.0.0.1, server: localhost, request: "CONNECT beacons.gcp.gvt2.com:443 HTTP/1.1", host: "beacons.gcp.gvt2.com:443"
