### ISSUE TITLE
What functions does this module implement?

### ISSUE THREAD

**Issue by ygm521** [chobits/ngx_http_proxy_connect_module#78]

**Comment by chobits** [comment]
This module makes nginx work as forward proxy server for HTTPS.
It implements this function via supporting HTTP CONNECT method, which is not supported by original nginx.

For details of  CONNECT tunnel, see https://en.wikipedia.org/wiki/HTTP_tunnel#HTTP_CONNECT_tunneling.

**Comment by chobits** [comment]
think it resolved.
