### ISSUE TITLE
2019/03/01 09:05:37 [error] 56#56: *79 upstream timed out (110: Operation timed out) while connecting to upstream(proxy_connect),

### ISSUE THREAD

**Issue by songshuone** [chobits/ngx_http_proxy_connect_module#80]

**Comment by songshuone** [comment]
big file post by proxy_connect

**Comment by chobits** [comment]
Hi,

This error message means proxy connect module tried to connect upstream peer but failed.
It only depends on connectivity of upstream peer.

**Comment by songshuone** [comment]
How to configure it?

**Comment by songshuone** [comment]
> Hi,
> 
> This error message means proxy connect module tried to connect upstream peer but failed.
> It only depends on connectivity of upstream peer.

How to configure it?

**Comment by chobits** [comment]
hi @songshuone 

> How to configure it?

This means your host canont connect upstream peer,  you should resolve this problem firstly. 

Proxy_connect module cannot fix this problem, it just reports it.

---
BTW, one helpful way is to set larger `proxy_connect_connect_timeout`. But this cannot resolve fundamental problem.

**Comment by chobits** [comment]
Also see another similar faq: https://github.com/chobits/ngx_http_proxy_connect_module/issues/35
