### ISSUE TITLE
Is it possible to support verification of client certificates?

### ISSUE THREAD

**Issue by bigboyq** [chobits/ngx_http_proxy_connect_module#81]
if add a new param to control whether check $ssl_client_verify, would be helpful authentication, 
such as
proxy_connect_ssl_client_verify on/off;   [default off]

if proxy_connect_ssl_client_verify on then check ssl_client_verify for each request, if failed, return 400, if successed, authenticated!

I think this function would be very helpful, thanks for considering.

**Comment by chobits** [comment]
Note that proxy_connect module does not parse the proxied tcp stream after CONNECT request.

Although it can be doable for ssl-client-verify if we think the proxied tcp stream is SSL protocol, but implementation is not easy. Current imeplementation is just proxing the raw stream, if we do ssl-client-veirfy, the proxy core should do much SSL working. 

I think a good way is that upstream peer does ssl-client-verify. It is real consumer of the raw stream.

**Comment by bigboyq** [comment]
May be I have some misunderstanding....
For my consideration, ssl-client-verify happens on the TLS layer, before CONNECT method be procedured. 
In my mind, CONNECT module only need to see the result of $ssl-client-verify, no much code work should be done.
I could describe one situation, which required this function
I have a nginx server, I could set 
```
    ssl_verify_client 		optional;
```
IMPORTANT, ssl_verify_client is a configure item, $ssl-client-verify is a variable, which indicates whether cert verify be succeed.
In the connect module, I could check $ssl_client_verify, if equal to 'SUCCESS', I process the connect method, otherwise, return 400
In the location /.well_known/ no $ssl_client_verify check required, as .acme.sh could use this path to renew my certificate
In the Location /, $ssl_client_verify is required, if 'SUCCESS', proxy_pass works, otherwise, return 404;

**Comment by chobits** [comment]
Will check it later, please wait:)

**Comment by bigboyq** [comment]
> Will check it later, please wait:)

Happy to wait

**Comment by chobits** [comment]
Hi, you can check [$ssl_client_verify](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#var_ssl_client_verify) in lua-nginx-module.

proxy_connect module can support lua-nginx-module:

![image](https://user-images.githubusercontent.com/623062/53855628-65e68400-4009-11e9-8502-29299ab19141.png)

**Comment by chobits** [comment]
> In the location /.well_known/ no $ssl_client_verify check required, as .acme.sh could use this path to renew my certificate
> In the Location /, $ssl_client_verify is required, if 'SUCCESS', proxy_pass works, otherwise, return 404;

Do you want proxy_connect module to check different location? 
Proxy_connect module cannot get location (proxied request URI) info from raw tcp stream.

**Comment by bigboyq** [comment]
> > In the location /.well_known/ no $ssl_client_verify check required, as .acme.sh could use this path to renew my certificate
> > In the Location /, $ssl_client_verify is required, if 'SUCCESS', proxy_pass works, otherwise, return 404;
> 
> Do you want proxy_connect module to check different location?
> Proxy_connect module cannot get location (proxied request URI) info from raw tcp stream.

I don't think connect module support location is a good idea, this function may made connect module more flexible but too heavy.
I think authentication support might be a useful enhancement, as authentication is quite common function.
Support $ssl_client_verify by lua may be a solution.
In my mind(neither right nor wrong), lua solution might be good, but authentication might be more common requirement, haha.
Anyway, wait your decision, if you decide to support, I wait. If not, I will try lua support:)

**Comment by chobits** [comment]
BTW, rewrite module still can work. For example configuration, it maybe:

```
if ($ssl_client_verify = "..." ) {
  return 400;
}
```

**Comment by bigboyq** [comment]
$request_method =
![image](https://user-images.githubusercontent.com/14234681/53860896-6852d900-401d-11e9-8bd0-b32afba1a2ee.png)
![image](https://user-images.githubusercontent.com/14234681/53860918-743e9b00-401d-11e9-9421-9a5f8d2569c8.png)
just let you know

**Comment by bigboyq** [comment]
It seems that, CONNECT method has no location, if I am wrong, let me know
Outside location, you can not specify verification for CONNECT method
As a result, we can handle GET/POST with authentication process, but CONNECT, not.

**Comment by bigboyq** [comment]
Related configuration pasted here, I think you could understand :P
```
ssl_verify_client 		on;
#ssl_verify_client		optional;
server {
    	listen 443 ssl;	
	proxy_connect;
	proxy_connect_allow all;
	proxy_connect_connect_timeout  10s;
	proxy_connect_read_timeout     10s;
	proxy_connect_send_timeout     10s;
	if ($ssl_client_verify != "SUCCESS")
		{
	#		if ($request_method = CONNECT)	{return 400;}
		}
	location / {
		#if ($ssl_client_verify != "SUCCESS") {return 404;}
		proxy_pass http://$host;
		proxy_set_header Host $host;
	}
    }

```

**Comment by chobits** [comment]
Try this configuration:

```
        set $ssl_client_verify_connect "$request_method $ssl_client_verify";
        if ($ssl_client_verify_connect ~ "CONNECT FAILED") { return 401; }
```

**Comment by bigboyq** [comment]
Funny solution, Finally configuration is 
```
	set $ssl_client_verify_connect "$request_method $ssl_client_verify";
	if ($ssl_client_verify_connect ~ "CONNECT FAILED") { return 401; }
	if ($ssl_client_verify_connect ~ "CONNECT NONE") { return 401; }
```

**Comment by chobits** [comment]
> In the connect module, I could check $ssl_client_verify, if equal to 'SUCCESS', I process the connect method, otherwise, return 400

I think this function is better to be implemented in nginx SSL core logic, should not be implemented in any 3rd module. But using `$ssl_client_verify` is a more flexible way to control client verification.

I found that most nginx user uses `$ssl_client_verify` to do client verification. For example, https://serverfault.com/questions/327002/how-to-use-ssl-verify-client-on-on-one-virtual-server-and-ssl-verify-client-off.

**Comment by bigboyq** [comment]
That's ok, I have seen the same topic before.
My configuration works properly, Thanks for the help, haha
I think I could close this issue.
