### ISSUE TITLE
[TODO] Variable timeout parameters

### ISSUE THREAD

**Issue by james-callahan** [chobits/ngx_http_proxy_connect_module#82]
Currently `proxy_connect_connect_timeout`, `proxy_connect_read_timeout` and `proxy_connect_send_timeout` need to be hard coded in the nginx template, could you make them variable (usable with `set`)?

(oops, I realised that these are `server` block parameters which I think makes them ineligible to be variables? either way I'd still like for them to be variable on a per connection basis)

**Comment by thibaultcha** [comment]
Maybe consider an FFI binding for LuaJIT instead?

**Comment by chobits** [comment]
FFI binding is good idea, but current implementation is hard to do.

Because connect_timeout/reasd_timeout is hard coded in worker-shared structure ngx_http_proxy_connect_loc_conf_t. Although FFI binding can modify this field, it works for other requests.

Will add this feature next commit.

**Comment by chobits** [comment]
Hi all,

This feature is implemented in https://github.com/chobits/ngx_http_proxy_connect_module/pull/85.

Also will be happy if anyone can review it for me:)

**Comment by chobits** [comment]
Hi all,

New feature has been merged into master.
See the documentation: https://github.com/chobits/ngx_http_proxy_connect_module#proxy_connect_connect_timeout-1

**Comment by james-callahan** [comment]
Awesome, thankyou!
