### ISSUE TITLE
What's the difference between proxy_pass and proxy_connect_address?

### ISSUE THREAD

**Issue by songshuone** [chobits/ngx_http_proxy_connect_module#84]

**Comment by chobits** [comment]
This module makes nginx work as forward proxy server for HTTPS.
It implements this function via supporting HTTP CONNECT method, which is not supported by original nginx.

For details of  CONNECT tunnel, see https://en.wikipedia.org/wiki/HTTP_tunnel#HTTP_CONNECT_tunneling.

**Comment by chobits** [comment]
a talk for this module: https://github.com/chobits/ngx_http_proxy_connect_module/issues/78

**Comment by chobits** [comment]
thinks it resolved, closing.
