### ISSUE TITLE
Unable to compile :(

### ISSUE THREAD

**Issue by jsEveryDay** [chobits/ngx_http_proxy_connect_module#98]
Any suggestions anyone?
I tried 1.15.12 with no luck, since 1.15.10 was supported by this branch, tried that too. Same results. No issues until --add-module is introduced.

![image](https://user-images.githubusercontent.com/16431055/56404339-1f08c280-6234-11e9-8fa5-81cf70e5e03e.png)

**Comment by chobits** [comment]
hi @jsEveryDay 

It seems that your nginx source is not patched , see this https://github.com/chobits/ngx_http_proxy_connect_module#select-patch  for more details.

**Comment by chobits** [comment]
1.15.12 has been supported, see this pull request & test case: https://github.com/chobits/ngx_http_proxy_connect_module/pull/101

**Comment by chobits** [comment]
hi @jsEveryDay 

Do you resolve this problem with right patch?

**Comment by chobits** [comment]
deactive, think it resolved

**Comment by jsEveryDay** [comment]
Sorry about the delayed response. Yes you are correct, the patch is not being applied correctly.
Could you please identify my issue? I am using Centos7 GNU patch 2.7.1

`yum install patch -y
wget http://nginx.org/download/nginx-1.15.12.tar.gz
tar -zxvf *.tar.gz
wget https://github.com/chobits/ngx_http_proxy_connect_module/blob/master/patch/proxy_connect_rewrite_101504.patch
cd nginx-1.15.12

patch -p1 < /root/nginx/proxy_connect_rewrite_101504.patch
**--Response = patch: **** Only garbage was found in the patch input.**

cd ../
git clone https://github.com/chobits/ngx_http_proxy_connect_module.git
cd nginx-1.15.12
./configure --add-module=/root/nginx/ngx_http_proxy_connect_module
make

Same errors`

**Comment by chobits** [comment]
> Sorry about the delayed response. Yes you are correct, the patch is not being applied correctly.
> Could you please identify my issue? I am using Centos7 GNU patch 2.7.1
> 
> `yum install patch -y
> wget http://nginx.org/download/nginx-1.15.12.tar.gz
> tar -zxvf *.tar.gz
> wget https://github.com/chobits/ngx_http_proxy_connect_module/blob/master/patch/proxy_connect_rewrite_101504.patch
> cd nginx-1.15.12
> 
> patch -p1 < /root/nginx/proxy_connect_rewrite_101504.patch
> **--Response = patch: **** Only garbage was found in the patch input.**
> 
> cd ../
> git clone https://github.com/chobits/ngx_http_proxy_connect_module.git
> cd nginx-1.15.12
> ./configure --add-module=/root/nginx/ngx_http_proxy_connect_module
> make
> 
> Same errors`

has been resolved in https://github.com/chobits/ngx_http_proxy_connect_module/issues/105
