### ISSUE TITLE
How to install this module on Windows?

### ISSUE THREAD

**Issue by OldBoyFromFDU** [chobits/ngx_http_proxy_connect_module#99]
I wanna upgrade this patch on Windows.But how to do it……On Linux we can ./configure &&make &&make install.Emmm....how to patch on Windows?

**Comment by OldBoyFromFDU** [comment]
I wanna upgrade this patch on Windows.But how to do it……On Linux we can ./configure &&make &&make install.Emmm....how to patch on Windows?

**Comment by chobits** [comment]
* patch  on windows: see this link: https://stackoverflow.com/questions/517257/how-do-i-apply-a-diff-patch-on-windows
* compile nginx on windows: see this link: http://nginx.org/en/docs/howto_build_on_win32.html
